---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
# For the accents é ù û etc
options(Encoding="latin1")
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R",encoding="latin1")
# Setting the current path
path_to_R_folder = file.path(
                             path_to_Savanna_structure_GEDI_folder,
                             "R"
                             )
setwd(path_to_R_folder)
getwd()

# Libraries
library(fst)
library(ggplot2)

# Chargement du tableau missing_data_percentages.csv

setwd(file.path(
                path_to_Savanna_structure_GEDI_folder,
                "figures"
                )
      )

missing_data_percentages <- read.csv("missing_data_percentages.csv",row.names=1)

setwd(path_to_R_folder)
```

```{r}
# Correlation matrices

setwd(path_to_GEDI_raw_data)

matrices_list <- list()
names = list()

for (i in 1:length(dir())){
#for (i in 1:1){

  name = dir()[i]
  corresponding_table = fst::read.fst(name)
  name <- substr(name, start = 1, stop = nchar(name) - 4)
  # to get rid of the ".fst" in the graph name
  print(name)
  
  TRUE_FALSE_is_fire_freq_NA <- is.na(corresponding_table[,"fire_freq"])
  corresponding_table["fire_freq_NA"] <- TRUE_FALSE_is_fire_freq_NA
  
  # If we want to replace the NA by zero at some point
  corresponding_table[which(TRUE_FALSE_is_fire_freq_NA),"fire_freq"] <- 0
  
  corresponding_table <- corresponding_table[
    complete.cases(
      corresponding_table[,c("x",
                             "y",
                             "rh98",
                             "canopy_cover",
                             "fire_freq",
                             "mean_precip",
                             "cv_rainfall",
                             "eff_rainfall",
                             "mean_temp",
                             "temp_range"
                             )]
                  ),]
  
  # get rid of NA rows
  
  correlation_matrix <- cor(x = corresponding_table[,c("x",
                                                       "y",
                                                       "rh98",
                                                       "canopy_cover",
                                                       "fire_freq",
                                                       "mean_precip",
                                                       "cv_rainfall",
                                                       "eff_rainfall",
                                                       "mean_temp",
                                                       "temp_range"
                                                       )]
                                                      )

  correlation_matrix <- round(correlation_matrix,2)

  print(as.data.frame(correlation_matrix))
  
  matrices_list[[i]] <- correlation_matrix
  names[i] <- name
  
  setwd(path_to_GEDI_raw_data)
  
}


# Get back to the R folder
setwd(path_to_R_folder)
```

```{r}
# Function to plot correlation matrix

display_matrix <- function(correlation_matrix,name){
  
  correlation_matrix[lower.tri(correlation_matrix)]<- NA
  
  correlation_matrix <- melt(correlation_matrix)
  
  ggheatmap <- ggplot(correlation_matrix, aes(Var2, Var1, fill = value)) +
   geom_tile(color = "white")+
   scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="correlation") +
   theme_minimal()+ # minimal theme
   theme(axis.text.x = element_text(angle = 45, vjust = 1, 
   size = 12, hjust = 1))+
   coord_fixed() +
  
  geom_text(aes(Var2, Var1, label = value), color = "black", size = 3) +
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.grid.major = element_blank(),
  panel.border = element_blank(),
  panel.background = element_blank(),
  axis.ticks = element_blank(),
  legend.justification = c(1, 0),
  legend.position = c(0.6, 0.7),
  legend.direction = "horizontal")+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
  title.position = "top", title.hjust = 0.5)) +
    
  ggtitle(name)
  
  return(ggheatmap)
}

```

```{r}
for (i in 1:length(matrices_list)){
  
  name <- names[[i]]
  
  plot <- display_matrix(
                         correlation_matrix = matrices_list[[i]],
                         name = name
                         )
  
    
  setwd(file.path(
                  path_to_Savanna_structure_GEDI_folder,
                  "figures",
                  "correlation_matrices",
                  "with_NA_replaced"
                  )
  )
  
  # ggsave(
  #      paste(name,".png"),
  #      plot = plot,
  #      bg='#ffffff'# pour ne pas avoir un fond gris moche
  #      )

  setwd(path_to_GEDI_raw_data)
}
```

```{r}
# Moyenne des matrices de corrélation

sum_matrix <- Reduce(`+`, matrices_list)
mean_correlation_matrix <- sum_matrix/length(matrices_list)

# Quelque part en faisant ça on donne un poids 1 à chaque tableau, qu'il contienne beaucoup de données ou pas, il serait préférable de tout concaténer et de faire un gros corrplot
```

```{r}
# Concaténation des tableaux puis matrice de corrélation

setwd(path_to_GEDI_raw_data)

matrices_list <- list()
names = list()

old_corresponding_table = data.frame(matrix(nrow=0,ncol=10))

colnames(old_corresponding_table) <-  c("x",
                                        "y",
                                        "rh98",
                                        "canopy_cover",
                                        "fire_freq",
                                        "mean_precip",
                                        "cv_rainfall",
                                        "eff_rainfall",
                                        "mean_temp",
                                        "temp_range")
                                              


for (i in 1:length(dir())){
#for (i in 1:1){

  name = dir()[i]
  corresponding_table = fst::read.fst(name)
  
  name <- substr(name, start = 1, stop = nchar(name) - 4)
  # to get rid of the ".fst" in the graph name
  print(name)
  
  TRUE_FALSE_is_fire_freq_NA <- is.na(corresponding_table[,"fire_freq"])
  corresponding_table["fire_freq_NA"] <- TRUE_FALSE_is_fire_freq_NA
  
  # If we want to replace the NA by zero at some point
  corresponding_table[which(TRUE_FALSE_is_fire_freq_NA),"fire_freq"] <- 0
  
  corresponding_table <- corresponding_table[
    complete.cases(
      corresponding_table[,c("x",
                             "y",
                             "rh98",
                             "canopy_cover",
                             "fire_freq",
                             "mean_precip",
                             "cv_rainfall",
                             "eff_rainfall",
                             "mean_temp",
                             "temp_range"
                             )]
                  ),]
  
  # get rid of NA rows
  
  corresponding_table = rbind(old_corresponding_table,corresponding_table)
  
  old_corresponding_table <- corresponding_table
  
  setwd(path_to_GEDI_raw_data)
  
}


# Get back to the R folder
setwd(path_to_R_folder)
```

```{r}
# print(nrow(corresponding_table))
# 45 189 435 : D

# Matrice de corrélation de toutes les données concaténées

correlation_matrix <- cor(x = corresponding_table[,c("x",
                                                     "y",
                                                     "rh98",
                                                     "canopy_cover",
                                                     "fire_freq",
                                                     "mean_precip",
                                                     "cv_rainfall",
                                                     "eff_rainfall",
                                                     "mean_temp",
                                                     "temp_range"
                                                     )]
                                                    )

correlation_matrix <- round(correlation_matrix,2)

print(as.data.frame(correlation_matrix))

plot <- display_matrix(
                       correlation_matrix = correlation_matrix,
                       name = "all_data"
                       )

print(plot)

setwd(file.path(
                path_to_Savanna_structure_GEDI_folder,
                "figures",
                "correlation_matrices",
                "with_NA_replaced"
                )
)
  
# ggsave(
#        paste("all_data.png"),
#        plot = plot,
#        bg='#ffffff'# pour ne pas avoir un fond gris moche
#        )
```

```{r}

```
