---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
# For the accents é ù û etc
options(Encoding="latin1")
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R",encoding="latin1")
# Setting the current path
path_to_R_folder = file.path(
                             path_to_Savanna_structure_GEDI_folder,
                             "R"
                             )
setwd(path_to_R_folder)
getwd()

# Libraries
library(fst)
library(ggplot2)

# Chargement du tableau

setwd(file.path(
                path_to_Savanna_structure_GEDI_folder,
                "figures"
                )
      )

missing_data_percentages <- read.csv("missing_data_percentages.csv",row.names=1)

setwd(path_to_R_folder)
```

```{r}

require("readxl")
require("terra")

setwd(file.path(
                path_to_Savanna_structure_GEDI_folder,
                "rawdata"
                )
      )

data_econame = read_excel("ecoregion_names.xlsx")

rast_ecoregion = rast("ras_ecoregion_names_africa.tif") # charger le raster des codes d'ecoregions

setwd(path_to_GEDI_raw_data)

name = dir()[1]
data_ecoregion = fst::read.fst(name) # charger la base de données
name <- substr(name, start = 1, stop = nchar(name) - 4) 

extract_rast = extract(rast_ecoregion,  data_ecoregion[,c("x","y")], method="simple") # extraire les codes d'ecoregions

data_ecoregion$econame_id =  extract_rast[,2] # insérer la colonne des codes extraits
# enfin faire la correspondance entre les codes et le nom à partir de ton fichier "data_econame"
```

```{r}

```
