---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R")
# Setting the current path
path_to_R_folder = file.path(
                             path_to_Savanna_structure_GEDI_folder,
                             "R"
                             )
setwd(path_to_R_folder)
getwd()

# Libraries
library(terra)
# Encoding :
print("é è û")
```

```{r}
complete_table = readRDS(
                         file = file.path(
                         path_to_Savanna_structure_GEDI_folder,
                         "subsampling30avril",
                         "subsampling_30avril.RDS"
                                          )
                         )

# To verify the standardisation and NAs :
summary(complete_table) # you can see among other things if there are 1 for canopy_cover 
colnames(complete_table)
colSums(is.na(complete_table))
```

```{r}
grid_giving_numbers_to_cell <- function(target_nrow,target_ncol,plot_grid=FALSE){
  
  # final sub-grid
  conserved = rep(TRUE,target_ncol*target_nrow)
  for (s in 1:length(conserved)){
    conserved[s] = s
  }
  
  if (plot_grid==TRUE){
    test_conserved <- matrix(conserved,ncol=target_ncol,byrow=TRUE)
    print(paste(target_nrow,"x",target_ncol,"matrix"))
    print(paste("length(conserved) =",length(conserved)))
    print(test_conserved)
  }
  
  return(conserved)
}

# # Tests of odd/even cases :
conserved <- grid_giving_numbers_to_cell(3,5,TRUE)
conserved <- grid_giving_numbers_to_cell(4,5,TRUE)
conserved <- grid_giving_numbers_to_cell(3,6,TRUE)
conserved <- grid_giving_numbers_to_cell(4,6,TRUE)
```

```{r}
require(sf)

# Saving all ecoregions sub (grid)-sampled in .RDS tables in transform data

cell <- 300*10**3
# 300km**2 par lambda 

save_things = TRUE

save_rds_files = save_things
save_center_cells_geojson = save_things
save_coords_TRUE_geojson = save_things

specific_table = complete_table

rownames(specific_table) = 1:nrow(specific_table)
colnames(specific_table)[1] = "x_center_small_cell"
colnames(specific_table)[2] = "y_center_small_cell"
# colnames(specific_table)[3] = "x_TRUE"
# colnames(specific_table)[4] = "y_TRUE"

specific_table <- cbind(
                      1:nrow(specific_table),
                      specific_table
                      )

colnames(specific_table)[1] = "index"

table_new <- data.frame(
                      index_point = specific_table$index,
                      coordxTRUE = specific_table$x_TRUE,
                      coordyTRUE = specific_table$y_TRUE
                      )

new_spatvector <- terra::vect(table_new, geom = c("coordxTRUE", "coordyTRUE"), crs = "+proj=longlat +datum=WGS84") 
# get new_spatvector "window" : xmin, xmax, ymin, ymax
window <- terra::ext(new_spatvector)
dx <- geodist::geodist(x = c(window[1],window[3]), y = c(window[2],window[3]), measure = "haversine")
dy <- geodist::geodist(x = c(window[1],window[3]), y = c(window[1],window[4]), measure = "haversine")
(target_ncol <- round(dx/cell))
# Guinean 10**4 cells : 133
(target_nrow <- round(dy/cell))
# Guinean 10**4 cells : 108

# 133*108 = 14364
# dimensions of y an z : 108, 333, 1  (nrow, ncol, nlyr)

#2) resampling
y <- terra::rast(new_spatvector, ncol = target_ncol, nrow = target_nrow, nlyr = 1)
values(y) <- grid_giving_numbers_to_cell(target_nrow,target_ncol)

intermediate_table = data.frame(cbind(values(y),crds(y)))
colnames(intermediate_table)[1] = "big_cell_number"
colnames(intermediate_table)[2] = "x_center_big_cell"
colnames(intermediate_table)[3] = "y_center_big_cell"

if (save_rds_files ==TRUE){

saveRDS(
      object = intermediate_table,
      file = file.path(
                       path_to_Savanna_structure_GEDI_folder,
                       "subsampling30avril",
                       "big_cell_300km_center_cells"
                       )
      )    

print("save rds DONE")

}


if (save_center_cells_geojson == TRUE){

sf_obj <- st_as_sf(intermediate_table,coords = c("x_center_big_cell", "y_center_big_cell"),crs = 4326)

st_write(
       sf_obj,
       file.path(path_to_Savanna_structure_GEDI_folder,
                 "subsampling30avril",
                 "big_cell_300km_center_cells.geojson"
                 ), delete_dsn = T
       )

print(".geojson DONE")
}

print(list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"big_subsampling30avril"),full.names=FALSE))
```

```{r}

```


```{r}

```
