---
title: "First test complete model"
output: html_document
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

```{r setup, echo=FALSE, include = FALSE}
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R")
getwd()
# Libraries
library(rjags)
library(dclone)
library(snow)
library(parallel)
library(doParallel)
```

```{r data_loading, echo=FALSE, include = FALSE}

table_region <- readRDS(
                file.path(
                  path_to_Savanna_structure_GEDI_folder,
                  "subsampling30avril",
                  "final_table_10km_associated_to_300km_cell.RDS")
                )

head(table_region,10)
# table(table_region$near_the_big_cell)

# si on veut conserver seulement certaines valeurs de précipitations :

# avant <- nrow(table_region)
# print(avant)
# table_region <- table_region[table_region[,"mean_precip"]<1200,]
# print(avant - nrow(table_region))

nrow(table_region)

data <- list(
             N = nrow(table_region), 
             prec_data = table_region$mean_precip,
             fire_data = table_region$fire_freq, 
             cc_data = table_region$canopy_cover
             ) 

# Quelle valeur de sigma_xi ?
{
par(mfrow=c(2,2))
for(sigma_xi in c(0.02,0.05,0.07,0.1)){

b = 0.47 ; offset = 3.47
G = seq(0,15,by=0.1)
proba_feu = 1 / (1+exp( - G*b + offset))
proba_feu = proba_feu + rnorm(length(proba_feu),0,sigma_xi)

plot(G,proba_feu,xlim=c(0,15),main=sigma_xi)}
# sigma_xi = 0.02 ça permet un peu de bruit mais pas trop
# sigma_xi = 0.1 ça permet beaucoup de bruit, sachant qu'en plus on ajuste b et offset 
# sigma_xi = 0.07 pas mal dans le genre assez bruité mais pas trop
# conclusion : sigma_xi ~ dunif(0.02,0.07) me paraît un range pas mal pour le prior
}

par(mfrow=c(1,1))
# prior de pt_inflexion_grass :
curve(dnorm(x,mean=600,sd=600),xlim=c(200,1400))

################################################
# Allures des pentes min et max de la prédiction herbacée
sigmo_pluie <- function(W,lambda,decalage){
  return(
    1/(1+exp(-lambda*(W-decalage)))
    )
}

W_values = seq(0,2000,by=20)
decalage = 600
K_G_pluie_max = 18 # t.ha-1
lambdas = c(0.0030,0.0088)

{
par(mfrow = c(1, 2))

for(i in 1:length(lambdas)){
   grass = K_G_pluie_max*sigmo_pluie(W_values,lambdas[i],decalage = decalage)
   plot(W_values, grass, col = "black",
        xlim=c(0,2000),ylim=c(0,K_G_pluie_max),
        xlab = "W", ylab = "G estimé",
        main=paste(lambdas[i]))
   abline(v=0,lty=2)
   abline(h=K_G_pluie_max,lty=2)
   # legend("topleft",paste0("K_G=",K_G_pluie_max))
}}

# nettoyage
rm(b)
rm(G)
rm(offset)
rm(sigma_xi)
```


```{r initialisation mcmc, echo=FALSE, include = FALSE}
# model and jags inference
vals <- data.frame(matrix(nrow=7,ncol=4)) # 7 variables pour 4 chaînes
rownames(vals) = c("K_G_t_f_pluie_max",
                   "b",
                   "offset",
                   "sigma_xi",
                   "log10delta_max",
                   "pt_inflexion_grass",
                   "lambda")

vals["K_G_t_f_pluie_max",] = c(18,20,22,24)

vals["b",] = c(0.48,0.49,0.50,0.49)
vals["offset",] = c(2.48,3,3,3.47)
vals["sigma_xi",] = c(0.03,0.065,0.04,0.06)

vals["log10delta_max",] = c(-4.5,-2.5,-3.6,-2.1)
vals["pt_inflexion_grass",] = c(900,600, 527, 446)
vals["lambda",] = c(0.0047,0.0067,0.0077,0.0037)

inits <- list(
 list(
       K_G_t_f_pluie_max = vals["K_G_t_f_pluie_max",1],

       b = vals["b",1],
       offset = vals["offset",1],
       sigma_xi = vals["sigma_xi",1],
       
       log10delta_max = vals["log10delta_max",1],
       pt_inflexion_grass = vals["pt_inflexion_grass",1],
       lambda = vals["lambda",1]
      ),
 
 list(
       K_G_t_f_pluie_max = vals["K_G_t_f_pluie_max",2],

       b = vals["b",2],
       offset = vals["offset",2],
       sigma_xi = vals["sigma_xi",2],
       
       log10delta_max = vals["log10delta_max",2],
       pt_inflexion_grass = vals["pt_inflexion_grass",2],
       lambda = vals["lambda",2]
      ),
 
 list(
       K_G_t_f_pluie_max = vals["K_G_t_f_pluie_max",3],

       b = vals["b",3],
       offset = vals["offset",3],
       sigma_xi = vals["sigma_xi",3],
       
       log10delta_max = vals["log10delta_max",3],
       pt_inflexion_grass = vals["pt_inflexion_grass",3],
       lambda = vals["lambda",3]
      ),
 list(
       K_G_t_f_pluie_max = vals["K_G_t_f_pluie_max",4],

       b = vals["b",4],
       offset = vals["offset",4],
       sigma_xi = vals["sigma_xi",4],
       
       log10delta_max = vals["log10delta_max",4],
       pt_inflexion_grass = vals["pt_inflexion_grass",4],
       lambda = vals["lambda",4]
      )
)

variables <- rownames(vals)
# donc là on explore un espace de dimension 8 sur (11*10**3)*(variable_data = 3) données
```


```{r estimation via jags, echo=FALSE, include = FALSE}
start = Sys.time()
print(start)

cl <- makeCluster((4))

registerDoParallel(cl)

# clusterExport(cl,"table_region")
clusterExport(cl,"data")
clusterExport(cl,"inits")
clusterExport(cl,"variables")

clusterEvalQ(cl,library(rjags))
clusterEvalQ(cl,library(coda))
clusterEvalQ(cl,library(runjags))
clusterEvalQ(cl,library(doParallel))
clusterEvalQ(cl,library(foreach))
clusterEvalQ(cl,library(iterators))

jags_res=foreach(i =1:4,.combine='mcmc.list',.multicombine=TRUE)%dopar%{
  as.mcmc(run.jags(file.path(path_to_Savanna_structure_GEDI_folder,"R","JAGS_models","model5.txt"),
                   monitor=variables,
                   data=data,
                   n.chains=1, # on envoie les chaînes séparemment sur chaque coeur
                   inits=dump.format(inits[[i]]),
                   burnin=500,
                   sample=1000,
                   thin=10,
                   tempdir=FALSE,
                   summarise=FALSE,
                   adapt = 500,
                   keep.jags.files=FALSE))

}

stopCluster(cl)

saveRDS(jags_res,
        file.path(
                  path_to_Savanna_structure_GEDI_folder,
                  "JAGS_outputs",
                  paste0("nouvelle_configuration",Sys.time(),".RDS")
                  )
        )

print(start-Sys.time())
rm(start)
```

```{r, visualisation sortie jags}
mcmc <- readRDS(
                file.path(
                          path_to_Savanna_structure_GEDI_folder,
                          "JAGS_outputs",
                          "nouvelle_configuration2024-07-02 13:22:16.543931.RDS"
                          )
                )
pdf(file.path(path_to_Savanna_structure_GEDI_folder,"JAGS_outputs",paste(Sys.time(),".pdf")))
# sink() to save the prints in the pdf

# performances et allures des chaînes :

{
print( summary(mcmc)$statistics )
for(j in 1:ncol(mcmc[[1]])){ plot(mcmc[,j],main=colnames(mcmc[[1]])[j]) }
}

gelman.diag(mcmc)
autocorr.plot(mcmc[[1]], ask = "TRUE",lag.max=1)

# données du livre Unesco
df_graphique = as.data.frame(matrix(nrow=4,ncol=2))
colnames(df_graphique) = c("pluie (mm yr-1)","biomasse (t.ha-1)")
df_graphique2 = df_graphique

df_graphique[1,] = c(400,2.3)
df_graphique[2,] = c(500,3)
df_graphique[3,] = c(600,4.2)
df_graphique[4,] = c(700,5.2)
df_graphique[5,] = c(750,6)
df_graphique[6,] = c(1000,8.75)

df_graphique2[1,] = c(400,2.3)
df_graphique2[2,] = c(500,3)
df_graphique2[3,] = c(600,4.3)
df_graphique2[4,] = c(700,6.5)
df_graphique2[5,] = c(800,9)
df_graphique2[6,] = c(900,12)
# fin des données du livre Unesco

W_lim_graph = 2600
W = seq(0,W_lim_graph,by=10)
point_inflexions = seq(500,1100,by=200)

K_G_t_f_pluie_max = summary(mcmc)$statistics["K_G_t_f_pluie_max",1]
pt_inflexion_grass = summary(mcmc)$statistics["pt_inflexion_grass",1]
lambda = summary(mcmc)$statistics["lambda",1]

delta_min = 10**-5
log10delta_max = summary(mcmc)$statistics["log10delta_max",1]
delta_max = 10**log10delta_max

deltas = seq(-5,log10delta_max,length=10)
deltas = 10**deltas
palette_deltas <- colorRampPalette(c("blue", "green"))(length(deltas))

{

par(mfrow = c(1, 2))

# graphique G estimé en fonction de la pluie
plot(
       x=c(0),
       y=c(0),
       xlim=c(0,W_lim_graph),
       ylim = c(0,K_G_t_f_pluie_max),
       xlab = "W",
       main = "G_hat",
       ylab = "G_hat"
       )

  lines(df_graphique,col="deeppink")
  lines(df_graphique2,col="deeppink")

  abline(v=pt_inflexion_grass,lty=2)
  abline(h=K_G_t_f_pluie_max*0.5,lty=2)
  abline(h=K_G_t_f_pluie_max,lty=2)
  
  S = rep(NA,length(W))
  for(u in 1:length(W)){ S[u] = ( 1 / ( 1+ exp(-lambda*(W[u]-pt_inflexion_grass)) ) ) }

  for(j in 1:length(deltas)){
    
     forest_effect_j = rep(NA,length(W))
     G_hat_j = rep(NA,length(W))
     K_fois_S = rep(NA,length(W))
     
     for(u in 1:length(W)){
       
       forest_effect_j[u] = 2/(1+ exp(deltas[j]*(W[u]-pt_inflexion_grass)) ) 
       G_hat_j[u] =  K_G_t_f_pluie_max*S[u]*forest_effect_j[u]
       K_fois_S[u] = K_G_t_f_pluie_max*S[u]
       }
     
     lines(W, G_hat_j, col = palette_deltas[j])
     lines(W, K_fois_S,lty=2,col="black")
  }

# légendes 
  
plot.new()

legend("center",
       legend = paste0("delta=",round(deltas,6)), 
       col = palette_deltas, 
       lty = 1,
       xpd = TRUE)

}

par(mfrow = c(1, 2))
# graphique probabilité feu en fonction de G estimé

G = seq(0.001,K_G_t_f_pluie_max,length=100)
b = summary(mcmc)$statistics["b",1]
offset = summary(mcmc)$statistics["offset",1]
p_feu = 1/( 1 + exp( -G*b + offset ) )

plot(
     G,
     p_feu,
     xlim=c(0,K_G_t_f_pluie_max),
     ylim=c(0,1),
     xlab = "G in (t.ha-1)",
     ylab = "proba feu",
     main = "new_omega"
     )
lines(G,1/( 1 + exp(-0.47*G+3.47)), col= "skyblue") # année 1995 (Wilgen 2000)
lines(G,1/(1 + exp(-0.51*G+2.47)), col = "red") # année 1996 (Wilgen 2000), severe fire weather conditions
# si on élargit un peu
lines(G,1/( 1 + exp(-0.47*G+4.00)), col= "cyan")
lines(G,1/(1 + exp(-0.51*G+2.00)), col = "darkred")

# avec le bruit sigma_xi
sigma_xi = summary(mcmc)$statistics["sigma_xi",1]
p_feu = p_feu + rnorm(length(p_feu),0,sigma_xi)

plot(
     G,
     p_feu,
     xlim=c(0,K_G_t_f_pluie_max),
     ylim=c(0,1),
     xlab = "G in (t.ha-1)",
     ylab = "proba feu",
     main = paste("sigma_xi =", round(sigma_xi,3))
     )

lines(G,1/( 1 + exp(-0.47*G+3.47)), col= "skyblue") # année 1995 (Wilgen 2000)
lines(G,1/(1 + exp(-0.51*G+2.47)), col = "red") # année 1996 (Wilgen 2000), severe fire weather conditions
# si on élargit un peu
lines(G,1/( 1 + exp(-0.47*G+4.00)), col= "cyan")
lines(G,1/(1 + exp(-0.51*G+2.00)), col = "darkred")

dev.off() # vient clore l'enregistrement pdf(...) de début de bloc de code

print( summary(mcmc)$statistics )
print( cor(mcmc[[1]]) )

borne_inf = c(18,0.47,2.47,0.02,-5,200,0.00017)
borne_sup = c(25,0.51,3.47,0.07,-2,1400,0.00088)
resume = rbind(borne_inf,summary(mcmc)$statistics[,1],borne_sup)
colnames(resume) = rownames(summary(mcmc)$statistics)
rownames(resume)[2] = "estimation"
print(resume)
```

```{r, resimulations}

mcmc2 = cbind(mcmc[[1]],mcmc[[2]],mcmc[[3]],mcmc[[4]])
# toutes les itérations des 4 chaînes post-burnin

I = nrow(table_region)
J = nrow(mcmc2)
# 
grass = matrix(nrow=I,ncol=J)
simulations_grass = matrix(nrow=I,ncol=J)
simulations_feu = matrix(nrow=I,ncol=J)
print_i_j_stuff = TRUE
# 
for(i in 1:I){
# #for(i in 1:10){
#   
  if(print_i_j_stuff == TRUE & i%%100 == 0){ print(paste("i",i,"/",I)) }
# 
  canopy_cover_i =  table_region[i,"canopy_cover"]
  pluie_i = table_region[i,"mean_precip"]
# 
for (j in 1:J){
# #  for (j in 1:10){ 
  
    delta_max_j = 10**(mcmc2[j,"log10delta_max"])
    pt_inflexion_grass = mcmc2[j,"pt_inflexion_grass"]
    
    canopy_influence_i_j = delta_min + canopy_cover_i*(delta_max_j-delta_min)
    sigmo_pluie_simu_i_j = ( 1/ (1+ exp(-mcmc2[j,"lambda"]*(pluie_i-pt_inflexion_grass)) ) )
    sigmo_forest_effect_simu_i_j = (2/(1+ exp(canopy_influence_i_j*(pluie_i-pt_inflexion_grass)) ) )
    grass_simu_i_j = mcmc2[j,"K_G_t_f_pluie_max"]*sigmo_pluie_simu_i_j*sigmo_forest_effect_simu_i_j
    # stockage de G estimé dans la matrice simulations_grass
    simulations_grass[i,j] = grass_simu_i_j
    
    p_feu_simu_i_j =  1/( 1 + exp( -grassB[i]*mcmc2[j,"b"] + mcmc2[j,"offset"] ) )
    effet_mesure = rnorm(n=1, mean = 0, sd = mcmc2[j,"sigma_xi"])
    simulations_feu[i,j] = p_feu_simu_i_j + effet_mesure
    # stockage de la proba de feu estimée pour cette valeur de G estimé
    # dans la matrice simulations_feu
#     
#     # comprenons ce qui va pas :
#     if(print_i_j_stuff == TRUE & i%%100 == 0 & j == 1){
#       
#     print(paste(i,table_region[i,"ecoregion"]))
#       
#     print(paste("canopy_cover_i",canopy_cover_i,
#                 "pluie_i",pluie_i))
#     
#     print(paste(  
#                 "grass_simu_i_j",grass_simu_i_j,
#                 "sigmo_pluie_simu_i_j",sigmo_pluie_simu_i_j,
#                 "sigmo_forest_effect_simu_i_j",sigmo_forest_effect_simu_i_j))
#     print(" ")
#     print(paste(  
#                 "a",a,
#                 "lambda",mcmc2[j,"lambda"],
#                 "pt_infl_grass",mcmc2[j,"pt_inflexion_grass"]))
#     print(paste(  
#                 "delta_max",mcmc2[j,"delta_max"],
#                 "delta_min",mcmc2[j,"delta_min"],
#                 "pt_inflexion_feu",mcmc2[j,"pt_inflexion_feu"]))
#     
#     print(paste(
#                 "p_feu_simu_i_j",p_feu_simu_i_j,
#                 "vraie valeur feu = ",table_region[i,"fire_freq"]))
#     
#     print(" ")
#     }
#     
  } # fin de la boucle j
} # fin de la boucle i
# 
saveRDS(simulations_grass,
        file.path(
                  path_to_Savanna_structure_GEDI_folder,
                  "JAGS_outputs",
                  paste0(Sys.time(),"simulations_grass.RDS"))
        )

saveRDS(simulations_feu,
        file.path(
                  path_to_Savanna_structure_GEDI_folder,
                  "JAGS_outputs",
                  paste0(Sys.time(),"simulations_feu.RDS"))
        )
```


```{r}
# # simulations_grass <- readRDS(
# #         file.path(
# #                   path_to_Savanna_structure_GEDI_folder,
# #                   "JAGS_outputs",
# #                   paste0(" "))
# #         )
# # 
# simulations_feu <- readRDS(
#         file.path(
#                   path_to_Savanna_structure_GEDI_folder,
#                   "JAGS_outputs",
#                   paste0(" "))
#         )
# 
# mean_simu_grass = rowMeans(simulations_grass)
# mean_simu_feu = rowMeans(simulations_feu)
# 
# plot(mean_simu_feu,table_region$fire_freq,xlim=c(0,1),ylim=c(0,1))
# summary(mean_simu_feu)
# summary(table_region$fire_freq)
# 
# 
# hist(mean_simu_feu,breaks=30)
# 
# cor(table_region$fire_freq,mean_simu_feu)
# 
# indices <- sort(table_region$fire_freq,index.return=TRUE)$ix
# fire_freq_sorted <- sort(table_region$fire_freq,index.return=TRUE)$x
# simu_feu_sorted <- mean_simu_feu[indices]
#   
# plot(fire_freq_sorted,simu_feu_sorted)
# 
# table(fire_freq_sorted)
# fire_freq_sorted[7000:1094]
# cor(fire_freq_sorted[7000:1094],simu_feu_sorted[7000:1094])
# 
# hist(mean_simu_grass,breaks=30)
# 
# plot(table_region[,"mean_precip"],mean_simu_grass)
# 
# summary(mean_simu_grass)
# pt_inflexion_feu = 3.83
# curve(x**2/(x**2+pt_inflexion_feu**2),xlim=c(0,20))
# abline(h=0.3)
```


```{r}
# prediction_feu = as.data.frame(cbind(table_region$x_TRUE,
#                        table_region$y_TRUE,
#                        table_region$fire_freq,
#                        mean_simu_feu))
# 
# colnames(prediction_feu) = c("x_TRUE","y_TRUE","fire","fire_simu")
# 
# cor(prediction_feu[,3:4])
# 
# feu_faible <- prediction_feu[prediction_feu[,"fire"]<0.1,]
# sum(is.na(feu_faible$fire))
# sum(is.na(feu_faible$fire_simu))
# cor(feu_faible[,3:4])
# 
# feu_fort <- prediction_feu[prediction_feu[,"fire"]>0.1,]
# cor(feu_fort[,3:4])
# 
# summary(prediction_feu$fire)
# sd(predictisf_obj <- st_as_sf(prediction_feu,coords = c("x_TRUE", "y_TRUE"),crs = 4326)
#   
#   st_write(
#     sf_obj,
#     file.path(path_to_Savanna_structure_GEDI_folder,
#               "geojson_files",
#               paste0("predictions_overleaf.geojson")
#     ), delete_dsn = T
#   )
# 
# cor(table_region$mean_precip,prediction_feu$simu)
```


