---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
# For the accents é ù û etc
options(Encoding="latin1")
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R",encoding="latin1")
# Setting the current path
path_to_R_folder = file.path(
                             path_to_Savanna_structure_GEDI_folder,
                             "R"
                             )
setwd(path_to_R_folder)
getwd()

# Libraries
library(fst)
library(ggplot2)

# Chargement du tableau missing_data_percentages.csv

setwd(file.path(
                path_to_Savanna_structure_GEDI_folder,
                "figures"
                )
      )

missing_data_percentages <- read.csv("missing_data_percentages.csv",row.names=1)

setwd(path_to_R_folder)
```

```{r}
# Visualisation des aires géographiques

setwd(path_to_GEDI_raw_data)

for (i in 1:length(dir())){
# for (i in 1:1){

  name = dir()[i]
  corresponding_table = fst::read.fst(name)
  name <- substr(name, start = 1, stop = nchar(name) - 4)
  # to get rid of the ".fst" in the graph name
  print(name)
  
  TRUE_FALSE_is_fire_freq_NA <- is.na(corresponding_table[,"fire_freq"])
  corresponding_table["fire_freq_NA"] <- TRUE_FALSE_is_fire_freq_NA
  
  # If we want to replace the NA by zero at some point
  # corresponding_table[which(TRUE_FALSE_is_fire_freq_NA),"fire_freq"] <- 0
  

  corresponding_table_without_fire_NA <- corresponding_table[
                                            complete.cases(
                                                           corresponding_table[,c("fire_freq")]
                                                          ),]

  plot1 <- ggplot() +
    
  geom_raster(data = corresponding_table_without_fire_NA ,
              aes(x = x, y = y,
                  fill = fire_freq)) +
  scale_fill_gradient(low = "pink", high = "red4") +

  scale_alpha(range = c(0.15, 0.65), guide = "none") +
  ggtitle("Fire_freq") +
  coord_quickmap()

  print(plot1)
  
  ###################
  plot2 <- ggplot() +
    
  geom_raster(data = corresponding_table ,
          aes(x = x, y = y,
              fill = fire_freq_NA)) +
      scale_fill_manual(values = c("red", "blue")) +
    
  scale_alpha(range = c(0.15, 0.65), guide = "none") +
  ggtitle("Fire_freq_NA") +
  coord_quickmap()

  print(plot2)
  
  setwd(file.path(
                  path_to_Savanna_structure_GEDI_folder,
                  "figures",
                  "fire_freq_NA_in_space"
                  )
  )
  
  ggsave(
       paste(name,"_fire_freq.png"),
       plot = plot1,
       bg='#ffffff'# pour ne pas avoir un fond gris moche
       )
  
  ggsave(
     paste(name,"_fire_freq_NA.png"),
     plot = plot2,
     bg='#ffffff'# pour ne pas avoir un fond gris moche
     )
  
  setwd(path_to_GEDI_raw_data)

}
```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
