---
title: "Regression results analysis"
output:
  html_document: default
  pdf_document: default
date: "2024-04-10"
---

```{r setup, include=FALSE}
# To hide source code
knitr::opts_chunk$set(echo = FALSE)
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R")
# source("R/paths.R")
path_to_R_folder = file.path(path_to_Savanna_structure_GEDI_folder,"R")
setwd(path_to_R_folder)

# Libraries
require(knitr)
library(fst)
library(rjags)
library(rstan)
stan_version()
library(stringr) 
library(brms)
library(corrplot)

# Rstan commands :
options(mc.cores = parallel::detectCores())
# if you are using rstan locally on a multicore machine and have plenty of RAM
# to estimate your model in parallel
rstan_options(auto_write = TRUE)
# which allows you to automatically save a bare version of a compiled Stan program
# to the hard disk so that it does not need to be recompiled (unless you change it).
# You will need to run these commands each time you load the rstan library.
require(shinystan)

print("..･ヾ(。￣□￣)ﾂ")
```

```{r rh98, include = TRUE}

list_of_ouputs = list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"outputs","rh98"),full.names=TRUE)[-1] # less all_Africa
names_of_outputs = list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"outputs","rh98"),full.names=FALSE)[-1] # less all_Africa

complete_table_region = readRDS(
                                  file.path(path_to_Savanna_structure_GEDI_folder,
                                  "rawdata_post_preprocessing",
                                  "6_ecoregions_without_duplicate_standardized_ONLY_over_6_ecoregions.RDS")
                                 )

for(i in 1:length(list_of_ouputs)){
  
  print(names_of_outputs[i])
  name = str_sub(names_of_outputs[i],end=-str_length("_regression_rh98.RDS")-1)
  
  sub_table_region <- readRDS(
                          file.path(
                                    path_to_Savanna_structure_GEDI_folder,
                                    "transformed_data",
                                    paste0(name,".RDS")
                                    )
                            )

  hist(sub_table_region$rh98,
       freq=FALSE,
       breaks=1:30,
       xlim=c(0,30),
       main=paste("rh98",name),
       col="green"
  )
  
  table_region <- complete_table_region[complete_table_region[,"ecoregion"] == name,]
   
  hist(table_region$rh98,
       freq=FALSE,
       breaks=1:30,
       xlim=c(0,30),
       main=paste("full rh98",name),
       col="green"
  )

} # END OF THE BIG LOOP
```

```{r canopy_cover, include = TRUE}

list_of_ouputs = list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"outputs","canopy_cover"),full.names=TRUE)
names_of_outputs = list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"outputs","canopy_cover"),full.names=FALSE)

complete_table_region = readRDS(
                                  file.path(path_to_Savanna_structure_GEDI_folder,
                                  "rawdata_post_preprocessing",
                                  "6_ecoregions_without_duplicate_standardized_ONLY_over_6_ecoregions.RDS")
                                 )

for(i in 1:length(list_of_ouputs)){
  
  print(names_of_outputs[i])
  name = str_sub(names_of_outputs[i],end=-str_length("_regression_canopy_cover.RDS")-1)
  
  sub_table_region <- readRDS(
                          file.path(
                                    path_to_Savanna_structure_GEDI_folder,
                                    "transformed_data",
                                    paste0(name,".RDS")
                                    )
                            )

  hist(sub_table_region$canopy_cover,
       freq=FALSE,
       breaks=seq(0,1,by=0.02),
       xlim=c(0,1),
       main=paste("canopy_cover",name),
       col = "darkgreen"
  )
  
   table_region <- complete_table_region[complete_table_region[,"ecoregion"] == name,]
   
  hist(table_region$canopy_cover,
       freq=FALSE,
       breaks=seq(0,1,by=0.02),
       xlim=c(0,1),
       main=paste("full canopy_cover",name),
       col = "darkgreen"
  )
  

} # END OF THE BIG LOOP
```

