---
title: "data_prep_for_variograms"
author: "lamonica-d"
date: "2024-03-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
# Getting the paths
source("R/paths.R")
# Libraries
library(fst)
library(brms)

(vect_names <- list.files(path = path_to_GEDI_raw_data))
```

```{r}
#load all data table
table <- readRDS(file = "rawdata/complete_corresponding_table_without_duplicate.RDS")
#select one ecoregion
(unique(table[,"ecoregion"]))
table_select <- table[table[,"ecoregion"] == "Sahelian_Acacia", ]
#transform lon/lat in meters
meter_coord <- proj4::project(xy = table_select[,1:2], proj = "+proj=utm +datum=WGS84")
table_select <- data.frame(table_select,x.meter = meter_coord$x, y.meter = meter_coord$y)
#from data.frame to spatvector
x <- terra::vect(table_select, geom = c("x.meter", "y.meter"), crs = "+proj=utm +datum=WGS84") 
#get x "window" : xmin, xmax, ymin, ymax
x_ext <- terra::ext(x)
#set a cell length, in meter
cell <- 20000
# dx <- geodist::geodist(x = c(x_ext[1],x_ext[3]), y = c(x_ext[2],x_ext[3]), measure = "haversine")
# dy <- geodist::geodist(x = c(x_ext[1],x_ext[3]), y = c(x_ext[1],x_ext[4]), measure = "haversine")
# (target_ncol <- round(dx/cell))
# (target_nrow <- round(dy/cell))
```

```{r}
x.random <- runif(n = 1, min = x_ext[1], max = x_ext[2])
y.random <- runif(n = 1, min = x_ext[3], max = x_ext[4])
random_extent <- terra::ext(c(x.random - cell/2, x.random + cell/2, y.random - cell/2, y.random + cell/2))
truc <- intersect(x, random_extent) #problème ici trop long
var_rh98 <- geoR::variog(coords = data.frame(truc$x.meter, truc$y.meter), data = truc$rh98)
```