---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
# For the accents é ù û etc
options(Encoding="latin1")
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R",encoding="latin1")
# Setting the current path
path_to_R_folder = file.path(
                             path_to_Savanna_structure_GEDI_folder,
                             "R"
                             )
setwd(path_to_R_folder)
getwd()

# Libraries
library(fst)
library(visdat)
# install.packages("visdat")
library(ggplot2)
# install.packages("betareg")
library(betareg)
# browseURL("https://www.jstatsoft.org/article/view/v034i02")

# Chargement du tableau missing_data_percentages.csv

setwd(file.path(
                path_to_Savanna_structure_GEDI_folder,
                "figures"
                )
      )

missing_data_percentages <- read.csv("missing_data_percentages.csv",row.names=1)

setwd(path_to_R_folder)
```


```{r}
# # Affichages histogrammes fire + rain + canopy_cover (en fait avec GGPLOT c'est mieux)
# 
# setwd(path_to_GEDI_raw_data)
# 
# for (i in 1:length(dir())){
# # for (i in 1:length(dir())){
#   
#   name = dir()[i]
#   corresponding_table = fst::read.fst(name)
#   name <- substr(name, start = 1, stop = nchar(name) - 4)
#   # to get rid of the ".fst" in the graph name
# 
# 
#   setwd(
#     
#         file.path(
#                   path_to_Savanna_structure_GEDI_folder,
#                   "figures",
#                   "cc_fire_rain"
#                   )
#         )
#   
#   # sauvagarde des trois histogrammes
#   #
#   # png(filename=paste0(name,"_cc_fire_rain.png"),width = 2000, height = 1000)
# 
#   par(mfrow= c(1,3))
# 
#   corresponding_table1 <- corresponding_table # all NA included in corresponding_table1
#   
#   # get rid of the canopy_cover NA
#   corresponding_table <- corresponding_table[complete.cases(corresponding_table[ , "canopy_cover"]),]
#   
#   if(
#     length(corresponding_table[,"canopy_cover"])>0 # s'il y a des données
#   ){hist(corresponding_table[,"canopy_cover"],breaks=40,main=name,xlab="canopy_cover")}
#   else{plot(c(0,0),main="que des NA pour canopy_cover",xlab="canopy_cover")}
# 
#   corresponding_table2 <- corresponding_table1[complete.cases(corresponding_table1[ , "fire_freq"]),]
#   # get rid of the fire_freq NA
# 
#   if(
#      length(corresponding_table2[,"fire_freq"])>0 # s'il y a des données
#     ){hist(corresponding_table2[,"fire_freq"],breaks=40,main=name,xlab="fire_freq")}
#   else{plot(c(0,0),main="que des NA pour le feu",xlab="fire_freq")}
# 
#   corresponding_table3 <- corresponding_table1[complete.cases(corresponding_table1[ , "mean_precip"]),]
#   # get rid of the mean_precip NA
# 
#   if(
#      length(corresponding_table3[,"mean_precip"])>0 # s'il y a des données
#     ){hist(corresponding_table3[,"mean_precip"],breaks=40,main=name,xlab="mean_precip")}
#   else{plot(c(0,0),main="que des NA pour la pluie",xlab="mean_precip")}
#   # 
#   # dev.off()
#   
#   setwd(path_to_GEDI_raw_data)
#   
# }
# 
# rm(corresponding_table)
# rm(corresponding_table1)
# rm(corresponding_table2)
# rm(corresponding_table3)
# 
# # Get back to the R folder
# setwd(path_to_R_folder)
```

```{r}
# Affichages avec GGPLOT histogrammes fire + rain + canopy_cover

require(ggplot2)
require(grid)
require(gridExtra)

setwd(path_to_GEDI_raw_data)

empty_df <- data.frame(c(0))
colnames(empty_df) <- "x"
# empty df to plot if 100% of NA

for (i in 1:length(dir())){
# for (i in 1:1){
  
  name = dir()[i]
  corresponding_table = fst::read.fst(name)
  name <- substr(name, start = 1, stop = nchar(name) - 4)
  # to get rid of the ".fst" in the graph name
  print(name)
  
  # print(missing_data_percentages[i,c("canopy_cover","rh98","fire_freq","mean_precip")])
  
  corresponding_table1 <- corresponding_table # all NA included in corresponding_table1
  
  corresponding_table <- corresponding_table[complete.cases(corresponding_table[ , "canopy_cover"]),]
  # get rid of the canopy_cover NA

  if(
    length(corresponding_table[,"canopy_cover"])>0 # s'il y a des données
  ){
    
    plot_cc <- ggplot(
                      corresponding_table,
                      aes(x=canopy_cover)
                      ) +
               geom_histogram(
                              position="identity",
                              bins = 30,
                              colour = "white",
                              fill = "forestgreen",
                              alpha = 0.6
                              ) +
      labs(x = paste0("canopy_cover (",
                 (1-missing_data_percentages[i,"canopy_cover"])*100,
                 "% of non-NA) "
                 # rownames(missing_data_percentages)[i]
                 )
      )
    }
  else{
  print("NO DATA")
  plot_cc<-ggplot(empty_df,aes(x=x)) +
           geom_histogram(position="identity")+
           labs(x="0% of non-NA for canopy_cover")
  }
  corresponding_table2 <- corresponding_table1[complete.cases(corresponding_table1[ , "fire_freq"]),]
  # get rid of the fire_freq NA

  if(
     length(corresponding_table2[,"fire_freq"])>0 # s'il y a des données
  ){
    plot_fire <- ggplot(
                  corresponding_table2,
                  aes(x=fire_freq)
                  ) +
                 geom_histogram(
                                position="identity",
                                bins = 30,
                                colour = "white",
                                fill = "red",
                                alpha = 0.6
                                ) +
      labs(x = paste0("fire_freq (",
                     (1-missing_data_percentages[i,"fire_freq"])*100,
                     "% of non-NA) "
                     # rownames(missing_data_percentages)[i]
                     )
      )
  }
  else{
  print("NO DATA")
  plot_fire<-ggplot(empty_df,aes(x=x)) +
                    geom_histogram(position="identity")+
                    labs(x="0% of non-NA for fire_freq")
  }
  corresponding_table3 <- corresponding_table1[complete.cases(corresponding_table1[ , "mean_precip"]),]
  # get rid of the mean_precip NA
  
  if(
     length(corresponding_table3[,"mean_precip"])>0 # s'il y a des données
  ){
    plot_rain <- ggplot(
              corresponding_table3,
              aes(x=mean_precip)
              ) +
             geom_histogram(
                            position="identity",
                            bins = 30,
                            colour = "white",
                            fill = "skyblue",
                            alpha = 0.6
                            ) +
      labs(x = paste0("mean_precip (",
                     (1-missing_data_percentages[i,"mean_precip"])*100,
                     "% of non-NA) "
                     # rownames(missing_data_percentages)[i]
                     )
      )
  }
  
  else{
  print("NO DATA")
  plot_rain<-ggplot(empty_df,aes(x=x)) +
             geom_histogram(position="identity")+
             labs(x="0% of non-NA for mean_precip")
  }
  corresponding_table4 <- corresponding_table1[complete.cases(corresponding_table1[ , "rh98"]),]
  # get rid of the rh98 NA (there's none)
  # 
  if(
     length(corresponding_table4[,"rh98"])>0 # s'il y a des données
  ){
    plot_rh98 <- ggplot(
              corresponding_table4,
              aes(x=rh98)
              ) +
             geom_histogram(
                            position="identity",
                            bins = 30,
                            colour = "white",
                            fill = "limegreen",
                            alpha = 0.6
             ) +
      labs(x = paste0("rh98 (",
                     (1-missing_data_percentages[i,"rh98"])*100,
                     "% of non-NA) "
                     # rownames(missing_data_percentages)[i]
                     )
      )
    }
  else{
  print("NO DATA")
  plotrh98<-ggplot(empty_df,aes(x=x)) +
                   geom_histogram(position="identity")+
                   labs(x="0% of non-NA for rh98")
  }
  
  # print(plot_cc)
  # print(plot_rh98)
  # print(plot_fire)
  # print(plot_rain)
  
  plot <- grid.arrange(
                       plot_cc, plot_rh98, plot_fire, plot_rain,
                       nrow = 2, ncol=2,
                       bottom = textGrob(name,gp=gpar(fontsize=20,font=1))
                       )

  setwd(

        file.path(
                  path_to_Savanna_structure_GEDI_folder,
                  "figures",
                  "hists_canopy_rain_fire"
                  )
        )
  
  ggsave(
         paste0(name,".png"),
         plot = plot,
         bg='#ffffff'# pour ne pas avoir un fond gris moche
         )

  setwd(path_to_GEDI_raw_data)
  
}

rm(corresponding_table)
rm(corresponding_table1)
rm(corresponding_table2)
rm(corresponding_table3)
rm(corresponding_table4)

# Get back to the R folder
setwd(path_to_R_folder)
```

```{r}

```

```{r}

```
