---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
# For the accents é ù û etc
options(Encoding="latin1")
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R",encoding="latin1")
# Setting the current path
path_to_R_folder = file.path(
                             path_to_Savanna_structure_GEDI_folder,
                             "R"
                             )
setwd(path_to_R_folder)
getwd()
```

```{r}
# Raw GEDI tables loading
library(fst)

setwd(path_to_GEDI_raw_data)

data_north_congo <- fst::read.fst("Northern_Congolian.fst")
data_guinee <- fst::read.fst("Guinean_forest-savanna.fst")

setwd(path_to_R_folder)
# Get back to the R folder
getwd()
```

```{r}
# Visualisation des données manquantes
# sur les deux premiers datasets

# install.packages("visdat")

# browseURL("https://cran.r-project.org/web/packages/visdat/vignettes/using_visdat.html")

library(visdat)

# vis_dat(data_north_congo,warn_large_data = FALSE)
# vis_miss semble plus intéressant que vis_dat en ce qui nous concerne

start <- Sys.time()

vis_miss(
         data_north_congo,
         show_perc = FALSE,
         warn_large_data =FALSE
         )

duree <- Sys.time() - start
print(duree)
# Time difference of 12.27327 secs

start <- Sys.time()

vis_miss(
         data_guinee,
         show_perc = FALSE,
         warn_large_data =FALSE
         )

duree <- Sys.time() - start
nb_lignes <- round(nrow(data_guinee),-3)
print(paste("nb_lignes :",nb_lignes))
print(duree)
# Time difference of 1.804423 mins
```

```{r}
# Visualisation des données manquantes
# sur tous les datasets

library(visdat)
library(ggplot2)

setwd(path_to_GEDI_raw_data)

print(dir())
print(length(dir()))

for (i in 1:length(dir())){
  # print(dir()[i])
  
  setwd(path_to_GEDI_raw_data)
  
  name = dir()[i]
  print(name)
  corresponding_table = fst::read.fst(name)
  size <- nrow(corresponding_table)
  
  setwd(file.path(
                  path_to_Savanna_structure_GEDI_folder,
                  "figures",
                  "visualisation_donnees_manquantes"
                  )
  )
  
  start <- Sys.time()

  name <- substr(name, start = 1, stop = nchar(name) - 4)
  # to get rid of the ".fst" in the graph name
  
  plot <- vis_miss(
                   corresponding_table,
                   show_perc = FALSE,
                   warn_large_data =FALSE
                   )
  ggsave(
         paste(name,"_NA.png"),
         plot = plot,
         bg='#ffffff'# pour ne pas avoir un fond gris moche
         )

  duree <- Sys.time() - start
  nb_lignes <- round(nrow(corresponding_table),-3)
  print(paste("nb_lignes :",nb_lignes))
  print(duree)
}

# Get back to the R folder
setwd(path_to_R_folder)
# Get back to the R folder
getwd()

# [1] "Sahelian_Acacia.fst"
# Erreur : impossible d'allouer un vecteur de taille 1.8 Go
```

```{r}


```