---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
# For the accents é ù û etc
options(Encoding="latin1")
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R",encoding="latin1")
# Setting the current path
path_to_R_folder = file.path(
                             path_to_Savanna_structure_GEDI_folder,
                             "R"
                             )
setwd(path_to_R_folder)
getwd()

# Libraries
library(fst)
library(visdat)
# install.packages("visdat")
library(ggplot2)
# install.packages("betareg")
library(betareg)
# browseURL("https://www.jstatsoft.org/article/view/v034i02")

# Chargement du tableau missing_data_percentages.csv

setwd(file.path(
                path_to_Savanna_structure_GEDI_folder,
                "figures"
                )
      )

missing_data_percentages <- read.csv("missing_data_percentages.csv",row.names=1)

setwd(path_to_R_folder)
```

```{r}
# Normalisation des données sur un exemple

setwd(path_to_GEDI_raw_data)
# print(dir())

name = dir()[16]
# Loading of the table :
corresponding_table = fst::read.fst(name)
name <- substr(name, start = 1, stop = nchar(name) - 4)
# to get rid of the ".fst" in the graph name
print(name)
# "Northern_Congolian"

# # Pour avoir le type des données :

# str(corresponding_table)
# sapply(corresponding_table, class)

# On enlève la variable "ecoregion" pour ne garder que les données numériques :
corresponding_table <- corresponding_table[,-11]
# On va même garder seulement ça pour commencer :
corresponding_table <- corresponding_table[,c("x",
                                              "y",
                                              "canopy_cover",
                                              "fire_freq",
                                              "mean_precip")
                                           ]
# On enlève les valeurs manquantes
corresponding_table <- na.omit(corresponding_table)
print(round(
            missing_data_percentages[name,c("canopy_cover","fire_freq","mean_precip")],
            2)
      )
# Normalisation et standardisation 
corresponding_table[,c("fire_freq","mean_precip")] <- scale(
corresponding_table[,c("fire_freq","mean_precip")],
center=TRUE,scale=TRUE)

# Vérification :
colMeans(corresponding_table)
apply(corresponding_table, MARGIN = 2, sd)
# 2 pour spécifier qu'on fait l'opération sur les colonnes (1 pour ligne)

#########################################################################

# canopy_cover dans [0,1] -> loi beta ?
# Gadget en ligne pour regarder la densité loi beta :
# browseURL("https://mathlets.org/mathlets/beta-distribution/")

# Il n'y a pas de loi beta dans glm :
# glm_result <- glm(
#                   canopy_cover ~ 1 + fire_freq + mean_precip,
#                   family = beta, # ça existe pas
#                   data = corresponding_table
#                   )

corresponding_table <- as.data.frame(corresponding_table)
```

```{r}
glm_result <- betareg(
                      canopy_cover ~ 1 + fire_freq + mean_precip,
                      link = "logit",
                      # link function in the mean model (mu)
                      # logit par défaut ??
                      data = corresponding_table
                      )
# "your dependent variable should take values that are strictly greater than 0 and strictly less than 1; they cannot be equal to 0 or equal to 1" cf :
# browseURL("https://stats.stackexchange.com/questions/496050/why-is-betareg-giving-invalid-dependent-variable-error")
```

```{r}
# Sur tous les jeux de données :

setwd(path_to_GEDI_raw_data)

print(dir())
print(length(dir()))

for (i in 1:1){
# for (i in 1:length(dir())){
  
  # print(dir()[i])
  
  name = dir()[i]
  print(name)
  corresponding_table = fst::read.fst(name)
  size <- nrow(corresponding_table)
  name <- substr(name, start = 1, stop = nchar(name) - 4)
  # to get rid of the ".fst" in the graph name
  
  start <- Sys.time()
  
  # glm_result <- ...
  
  duree <- round (Sys.time() - start,1)
  
  nb_lignes <- round(nrow(corresponding_table),-3)
  print(paste("nb_lignes :",nb_lignes))
  print(duree)
  
  print(summary(glm_result))
}

# Get back to the R folder
setwd(path_to_R_folder)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
