---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R")
# Setting the current path
path_to_R_folder = file.path(
                             path_to_Savanna_structure_GEDI_folder,
                             "R"
                             )
setwd(path_to_R_folder)
getwd()

# Libraries
library(fst)
# Encoding :
print("é è û")
```
```{r}
# Concatenation of all data in complete_corresponding_table

complete_corresponding_table = data.frame(matrix(nrow=0,ncol=9))

colnames(complete_corresponding_table) <-  c("x",
                                             "y",
                                             "rh98",
                                             "canopy_cover",
                                             "fire_freq",
                                             "mean_precip",
                                             "mean_temp",
                                             "ecoregion",
                                             "fire_freq_NA")

for (i in 1:length(dir(path_to_GEDI_raw_data))){
#for (i in 1:1){

  name = dir(path_to_GEDI_raw_data)[i]

  corresponding_table = fst::read.fst(file.path(path_to_GEDI_raw_data,name))
  
  # Let's only keep the following columns :
  
  corresponding_table <- corresponding_table[ ,c("x",
                                                 "y",
                                                 "rh98",
                                                 "canopy_cover",
                                                 "fire_freq",
                                                 "mean_precip",
                                                 "mean_temp",
                                                 "ecoregion"
                                                 )]
  
  # Let's get rid of the ".fst" in the graph name
  name <- substr(name, start = 1, stop =  nchar(name) - 4)
  print(name)
  
  # Creation of a "fire_freq_NA" column and NA fire_freq replacement by 0s :
  
  TRUE_FALSE_is_fire_freq_NA <- is.na(corresponding_table[,"fire_freq"])
  corresponding_table["fire_freq_NA"] <- TRUE_FALSE_is_fire_freq_NA
  corresponding_table[which(TRUE_FALSE_is_fire_freq_NA),"fire_freq"] <- 0
  
  # Let's keep only the complete rows :
  # (45 millions of rows if we do this, 48 without this)
  
  corresponding_table <- corresponding_table[
    complete.cases(
      corresponding_table[,c("x",
                             "y",
                             "rh98",
                             "canopy_cover",
                             "fire_freq",
                             "mean_precip",
                             "mean_temp",
                             "ecoregion",
                             "fire_freq_NA"
                             )]
                  ),]

  
  # Concatenation of corresponding_table with the previous ones :
  
  complete_corresponding_table = rbind(complete_corresponding_table,corresponding_table)
  
}

rm(TRUE_FALSE_is_fire_freq_NA)
```
```{r}
# Y a-t-il des doublons ?

# nrow(complete_corresponding_table)
# [1] 45727445
# nrow(unique(complete_corresponding_table[c("x","y")]))
# [1] 45724087
# attention ça a fait chauffer ma machine ce truc...
# ah quelques doublons quand même sur les x et y avec des valeurs un peu différentes pour les autres variables
# nrow(unique(complete_corresponding_table))
# [1] 45727445
# duplicates <- complete_corresponding_table[duplicated(complete_corresponding_table[ , c("x","y")]),]    
# en fait ça a l'air d'être des dupliqués sur x OU y alors qu'on veut x ET y
# require(dplyr)
# duplicates2 <- complete_corresponding_table %>% distinct(x, y, .keep_all = TRUE)
# [1] 45724087
# hum, je veux voir les "doublons" pour être sûr

# require(janitor)
# duplicates <- janitor::get_dupes(complete_corresponding_table, "x", "y")
# # prend 5 minutes
# nrow(complete_corresponding_table)
# # [1] 45727445
# nrow(duplicates)
# # [1] 6716
# nrow(complete_corresponding_table) - nrow(duplicates)/2 # si on garde 1 duplicat sur 2
# # [1] 45724087

# without_duplicate <- unique(complete_corresponding_table[c("x","y")])
# same as the previous line but keeping other columns :
require(dplyr)
without_duplicate <- complete_corresponding_table %>% distinct(x, y, .keep_all = TRUE)
nrow(without_duplicate)
# [1] 45724087

# without_duplicate2 <- unique(complete_corresponding_table[c("x")])
# 8 400 du coup oui la commande unique(complete_corresponding_table[c("x","y")]) semble être la bonne,
# d'autant qu'elle redonne 45724087 le bon nombre de lignes 45727445 - 6716/2
# de même pour complete_corresponding_table %>% distinct(x, y, .keep_all = TRUE)
# car ok <- complete_corresponding_table %>% distinct(x, .keep_all = TRUE) donne 8 400 aussi
```

```{r}
# saveRDS(
#         object = without_duplicate,
#         file = file.path(
#                          path_to_Savanna_structure_GEDI_folder,
#                          "rawdata",
#                          "complete_corresponding_table_without_duplicate.RDS"
#                          )
#         )
# 
# without_duplicate <- readRDS(
#                               file.path(
#                                         path_to_Savanna_structure_GEDI_folder,
#                                         "rawdata",
#                                         "complete_corresponding_table_without_duplicate.RDS"
#                                         )
#                               )
```

```{r}
# Vérification qu'il n'y a pas de doublons :

without_duplicate = readRDS(file = file.path(
                                             path_to_Savanna_structure_GEDI_folder,
                                             "rawdata",
                                             "complete_corresponding_table_without_duplicate.RDS"
                                             )
                            )

head(without_duplicate)

require(janitor)
duplicates <- janitor::get_dupes(without_duplicate, "x", "y")
# On doit avoir le message :
# -> No duplicate combinations found of: x, y
```

```{r}
# Standardisation des données :

sub_table <- readRDS(file = file.path(
                                       path_to_Savanna_structure_GEDI_folder,
                                       "rawdata",
                                       "complete_corresponding_table_without_duplicate.RDS"
                                       )
                     )

sub_table = cbind(sub_table,as.vector(scale(sub_table$fire_freq, center = TRUE, scale = TRUE)))
sub_table = cbind(sub_table,as.vector(scale(sub_table$mean_precip, center = TRUE, scale = TRUE)))
sub_table = cbind(sub_table,as.vector(scale(sub_table$mean_temp, center = TRUE, scale = TRUE)))

colnames(sub_table)
ncol(sub_table)

colnames(sub_table)[10] = "fire_freq_std"
colnames(sub_table)[11] = "mean_precip_std"
colnames(sub_table)[12] = "mean_temp_std"

colnames(sub_table)

summary(sub_table)
colnames(sub_table)

saveRDS(
        object = sub_table,
        file = file.path(
                         path_to_Savanna_structure_GEDI_folder,
                         "rawdata",
                         "complete_corresponding_table_without_duplicate_standardized.RDS"
                         )
        )
```

```{r}
# # List of all ecoregions :
# unique(without_duplicate[,"ecoregion"])
# 
# # Selection of ecoregions :
# table_Sahelian_Acacia <- without_duplicate[without_duplicate[,"ecoregion"] == "Sahelian_Acacia", ]
# nrow(table_Sahelian_Acacia)
# table_West_Sudanian <- without_duplicate[without_duplicate[,"ecoregion"] == "West_Sudanian", ]
# nrow(table_West_Sudanian)
# table_Guinean <- without_duplicate[without_duplicate[,"ecoregion"] == "Guinean_forest-savanna", ]
# nrow(table_Guinean)
# 
# # "Sahelian_Acacia" : 21 422 708 points
# # "West_Sudanian" : 6 967 519 points
# # "Guinean_forest-savanna" : 3 248 787 points
```

```{r}

```

```{r}

```