---
title: "Regression results analysis"
output:
  html_document: default
  pdf_document: default
date: "2024-04-10"
---

```{r setup, include=FALSE}
# To hide source code
knitr::opts_chunk$set(echo = FALSE)
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R")
# source("R/paths.R")
path_to_R_folder = file.path(path_to_Savanna_structure_GEDI_folder,"R")
setwd(path_to_R_folder)

# Libraries
require(knitr)
library(fst)
library(rjags)
library(rstan)
stan_version()
library(stringr) 
library(brms)
library(corrplot)

# Rstan commands :
options(mc.cores = parallel::detectCores())
# if you are using rstan locally on a multicore machine and have plenty of RAM
# to estimate your model in parallel
rstan_options(auto_write = TRUE)
# which allows you to automatically save a bare version of a compiled Stan program
# to the hard disk so that it does not need to be recompiled (unless you change it).
# You will need to run these commands each time you load the rstan library.
require(shinystan)

print("..･ヾ(。￣□￣)ﾂ")
```

```{r time, include=TRUE}
print(Sys.time())
```

```{r Summaries and chains, include=TRUE}
lancer_shinystan = FALSE
print_one_stancode_example = TRUE
## Choose the chosen outputs by uncommenting one of those lines :

variable_names = c("rh98","canopy_cover")
# variable_names = c("rh98")
# variable_names = c("canopy_cover")

for (variable_name in variable_names){
print(paste("explicated variable of regression :",variable_name))
  
list_of_ouputs = list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"outputs",variable_name),full.names=TRUE)
names_of_outputs = list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"outputs",variable_name),full.names=FALSE)

print(paste("for ",names_of_outputs))
if(print_one_stancode_example == TRUE){
      # we put an example of the stancode of one of the zone, which is the same for all the same regressions :
      print("########################################")
      print("########################################")
      print("########################################")
      mcmc_output <- readRDS(list_of_ouputs[1])
      print(paste("below, stancode for",names_of_outputs[1]))
      print(stancode(mcmc_output))
      print("########################################")
      print("########################################")
      print("########################################")
}

print(" ")
print(" ")
for(i in 1:length(list_of_ouputs)){
  print(names_of_outputs[i])
  print("########################################")
  
  mcmc_output <- readRDS(list_of_ouputs[i])
  print(summary(mcmc_output))
  plot(mcmc_output,ask=FALSE)
  
  if(lancer_shinystan == TRUE ){launch_shinystan(mcmc_output)}
  print("########################################")
} # end of the regression for one variable

}
```

```{r Predictive check for Gamma densities, include=TRUE}

print_i_j_stuff = FALSE
# don't if you knit it...

list_of_ouputs = list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"outputs","rh98"),full.names=TRUE)
names_of_outputs = list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"outputs","rh98"),full.names=FALSE)

## For tests :
list_of_ouputs = list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"outputs","rh98"),full.names=TRUE)[7]
names_of_outputs = list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"outputs","rh98"),full.names=FALSE)[7]

print(paste("Gamma regressions for ",names_of_outputs))
print("########################################")
print("########################################")
print("########################################")

for(i in 1:length(list_of_ouputs)){
  print(names_of_outputs[i])
  print("########################################")
  
  mcmc_output <- readRDS(list_of_ouputs[i])
  mcmc_values <- as.data.frame(mcmc_output)
  J = nrow(mcmc_values)
  
  {
    table_region <- readRDS(
                          file.path(
                                    path_to_Savanna_structure_GEDI_folder,
                                    "transformed_data",
                                    paste0(
                                          str_sub(names_of_outputs[i],
                                                  end=-str_length("_regression_rh98.RDS")-1
                                                  ),
                                          ".RDS"
                                          )
                                    )
                            )
    
    table_region <- cbind(subset(table_region,select=rh98),
                          as.data.frame(matrix(nrow=nrow(table_region),ncol=3)),
                          subset(table_region,select=-rh98)
                          )
    colnames(table_region)[2] = c("pred_rh98_quantile_inf")
    colnames(table_region)[3] = c("pred_rh98_median")
    colnames(table_region)[4] = c("pred_rh98_quantile_sup")
    
    I = nrow(table_region)
  }
  
  table_region_rows = as.matrix(
                       cbind(rep(1,nrow(table_region)),
                          subset(table_region, select = c(fire_freq_std,mean_precip_std))
                            )
                                ) 
  
  linear_predictors_for_one_beta_draw_per_column = c()
  for(iter in 1:J){
    if(print_i_j_stuff == TRUE){ print(paste("iter",iter,"/",J)) }
    linear_predictors_for_one_beta_draw_per_column <- cbind(linear_predictors_for_one_beta_draw_per_column,
                  table_region_rows%*%t(mcmc_values[iter,c("b_Intercept","b_fire_freq_std","b_mean_precip_std")]))
  }
  
  print("dim(linear_predictors_for_one_beta_draw_per_column)")
  print(dim(linear_predictors_for_one_beta_draw_per_column))
  print("(nb_donnes I * nb_iter_mcmc J)")
  
  simulations = matrix(nrow=nrow(linear_predictors_for_one_beta_draw_per_column),
                      ncol=ncol(linear_predictors_for_one_beta_draw_per_column))
  
  linear_predictors_beta_mean = table_region_rows%*%as.matrix(summary(mcmc_output)$fixed$Estimate)
  simulation_beta_mean = matrix(nrow=I,ncol=1)
  shape_for_beta_mean = summary(mcmc_output)$spec_pars$Estimate
  
  # prediction for beta_mean
  for(i in 1:I){
    
  simulation_beta_mean[i,1] <- rgamma(n=1,
                             shape = shape_for_beta_mean, 
                             scale = exp(linear_predictors_beta_mean[i])/shape_for_beta_mean)
  }
  
  # predictions for all betas : for all i,j we make a gamma draw
  for(i in 1:I){
    if(print_i_j_stuff == TRUE){ print(paste("i",i,"/",I)) }
          
    for(j in 1:J){
      # mu += Intercept + Xc * b;
      # mu = exp(mu);
      # target += gamma_lpdf(Y | shape, shape ./ mu);
      
      shape <- mcmc_values[j,"shape"]
      simulations[i,j] <- rgamma(n=1,shape = shape, scale = exp(linear_predictors_for_one_beta_draw_per_column[i,j])/shape)
      
    }
    if(print_i_j_stuff == TRUE){print(paste("pour",J,"j"))}
  }
  
  # Quantiles for each simulation j
  {
  for(i in 1:I){
    table_region[i,c("pred_rh98_quantile_inf",
                     "pred_rh98_median",
                     "pred_rh98_quantile_sup")] <- quantile(simulations[i,], probs = c(0.05,0.5,0.95))
    }
  
  
    plot(1:I,
         table_region$rh98,
         xlab="i",
         ylab="rh98"
    )
    lines(1:I,table_region[,"pred_rh98_median"],col="pink",lty=1)
    lines(1:I,table_region[,"pred_rh98_quantile_inf"],col="blue",lty=2)
    lines(1:I,table_region[,"pred_rh98_quantile_sup"],col="darkblue",lty=2)
  }
  
  # Ordered :
  {

  indices_of_increasing_rh98 <- sort(table_region$rh98, index.return=TRUE)$ix
  ordered_table_region <- table_region[indices_of_increasing_rh98,]
  
    plot(1:I,
         ordered_table_region$rh98,
         xlab="i",
         ylab="rh98"
    )
    lines(1:I,ordered_table_region[,"pred_rh98_median"],col="pink",lty=1)
    lines(1:I,ordered_table_region[,"pred_rh98_quantile_inf"],col="blue",lty=2)
    lines(1:I,ordered_table_region[,"pred_rh98_quantile_sup"],col="darkblue",lty=2)
  }
  
  ####### Sur les n premières valeurs

  n = min(100,nrow(table_region))
  # for some datasets, there are less than 100 points...
  
  {
    plot(1:n,
         table_region$rh98[1:n],
         xlab="i",
         ylab="rh98",
         ylim=c(0,30)
    )
    lines(1:n,table_region[1:n,"pred_rh98_median"],col="pink",lty=1)
    lines(1:n,table_region[1:n,"pred_rh98_quantile_inf"],col="blue",lty=2)
    lines(1:n,table_region[1:n,"pred_rh98_quantile_sup"],col="darkblue",lty=2)
  
    indices_of_increasing_rh98 <- sort(table_region$rh98, index.return=TRUE)$ix
    ordered_table_region <- table_region[indices_of_increasing_rh98,]
    
    plot(1:n,
         ordered_table_region$rh98[1:n],
         xlab="i",
         ylim=c(0,30)
    )
    lines(1:n,ordered_table_region[1:n,"pred_rh98_median"],col="pink",lty=1)
    lines(1:n,ordered_table_region[1:n,"pred_rh98_quantile_inf"],col="blue",lty=2)
    lines(1:n,ordered_table_region[1:n,"pred_rh98_quantile_sup"],col="darkblue",lty=2)
  }

  # 5 plots of reality vs predicted
  nb_of_plots = 5
  {
  
  print("mean(table_region$rh98)")
  print(mean(table_region$rh98))
  print("sd(table_region$rh98)")
  print(sd(table_region$rh98))
  
  for(j in sample(1:J,nb_of_plots,replace=FALSE)){
  
                              hist(table_region$rh98,
                                   freq=FALSE,
                                   breaks=40,
                                   xlim=c(0,30),
                                   main="true rh98"
                              )
                              
                              hist(simulations[,j],
                                   freq=FALSE,
                                   breaks=40,
                                   xlim=c(0,30),
                                   main = paste("betas n°",j)
                              )
                              
                              # print mean and sd vs truth
                              {
                              print(paste(
                                "mean(simulations[,j]) ( truth =",
                                round(mean(table_region$rh98),3),
                                ")"
                                ))
                              print(round(mean(simulations[,j]),3))
                              print(paste(
                                "sd(simulations[,j]) ( truth =",
                                round(sd(table_region$rh98),3),
                                ")"
                                ))
                              print(round(sd(simulations[,j]),3))
                              }
                              
                              # # predicted vs truth
                              # {plot(table_region$rh98,
                              #       simulations[,j],
                              #       xlim=c(0,30),
                              #       ylim=c(0,30),
                              #       main = paste("betas n°",j,"cor=",
                              #          round(cor(table_region$rh98,simulations[,j]),
                              #                2)
                              #          )                                                 
                              # )
                              #   abline(0,1,col="red")}
                              # 
                              # sample_thing <- sample(1:I,40,replace=FALSE)
                              # 
                              # # just prediction of 40 random points
                              # {plot(table_region[sample_thing,"rh98"],
                              #       simulations[sample_thing,j],
                              #       xlim=c(0,30),
                              #       ylim=c(0,30),
                              #       main = paste("betas n°",j,"cor=",
                              #          round(cor(table_region$rh98,simulations[,j]),
                              #                2)
                              #          )
                              # )
                              #   abline(0,1,col="red")}
                              
                              
  } # end of the loop
  
    # predicted vs truth
    {plot(table_region$rh98,
          simulation_beta_mean,
          xlim=c(0,30),
          ylim=c(0,30),
          main = paste("cor=",
             round(cor(table_region$rh98,simulation_beta_mean),
                   2)
             )
    )
      abline(0,1,col="red")}

    sample_thing <- sample(1:I,40,replace=FALSE)

    # just prediction of 40 random points
    {plot(table_region[sample_thing,"rh98"],
          simulation_beta_mean[sample_thing],
          xlim=c(0,30),
          ylim=c(0,30),
          main = paste("40 random points; cor=",
             round(cor(table_region$rh98,simulation_beta_mean),
                   2)
             )
    )
      abline(0,1,col="red")}
  
  
  }
  
  moyennes <- vector(length = J)
  ecarts_types <- vector(length = J)
  
  for(j in 1:J){
    moyennes[j] <- mean(simulations[,j])
    ecarts_types[j] <- sd(simulations[,j])
    }
  
  # Histogramme des moyennes
  {hist(moyennes,
        freq=FALSE,
        breaks=50,
        xlim=c(min(moyennes)-1,max(moyennes)+1),
        main=paste(round(mean(table_region$rh98),3),"; simus=",round(mean(moyennes),3))
        )
    abline(v=mean(moyennes),
           col="black")
    
    abline(v=mean(table_region$rh98),
           col="blue")}
  
  # Histogramme des écarts-types
  {hist(ecarts_types,
        freq=FALSE,
        breaks=50,
        xlim=c(min(ecarts_types)-1,max(ecarts_types)+1),
        main=paste(round(sd(table_region$rh98),3),"; simus=",round(mean(ecarts_types),3))
        )
    abline(v=mean(ecarts_types),
           col="black")
    abline(v=sd(table_region$rh98),
           col="blue")}


} # END OF THE BIG LOOP
```

```{r Predictive check for Beta densities, include=TRUE}

print_i_j_stuff = TRUE
# don't if you knit it...

list_of_ouputs = list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"outputs","canopy_cover"),full.names=TRUE)
names_of_outputs = list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"outputs","canopy_cover"),full.names=FALSE)

## For tests :
list_of_ouputs = list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"outputs","canopy_cover"),full.names=TRUE)[7]
names_of_outputs = list.files(path = file.path(path_to_Savanna_structure_GEDI_folder,"outputs","canopy_cover"),full.names=FALSE)[7]

print(paste("Beta regressions for ",names_of_outputs))
print("########################################")
print("########################################")
print("########################################")

for(i in 1:length(list_of_ouputs)){
  print(names_of_outputs[i])
  print("########################################")
  
  mcmc_output <- readRDS(list_of_ouputs[i])
  mcmc_values <- as.data.frame(mcmc_output)
  J = nrow(mcmc_values)
  
  {
    table_region <- readRDS(
                          file.path(
                                    path_to_Savanna_structure_GEDI_folder,
                                    "transformed_data",
                                    paste0(
                                          str_sub(names_of_outputs[i],
                                                  end=-str_length("_regression_canopy_cover.RDS")-1
                                                  ),
                                          ".RDS"
                                          )
                                    )
                            )
    
    table_region <- cbind(subset(table_region,select=canopy_cover),
                          as.data.frame(matrix(nrow=nrow(table_region),ncol=3)),
                          subset(table_region,select=-canopy_cover)
                          )
    colnames(table_region)[2] = c("pred_canopy_cover_quantile_inf")
    colnames(table_region)[3] = c("pred_canopy_cover_median")
    colnames(table_region)[4] = c("pred_canopy_cover_quantile_sup")
    
    I = nrow(table_region)
  }
  
  table_region_rows = as.matrix(
                       cbind(rep(1,nrow(table_region)),
                          subset(table_region, select = c(fire_freq_std,mean_precip_std))
                            )
                                ) 
  
  linear_predictors_for_one_beta_draw_per_column = c()
  for(iter in 1:J){
    if(print_i_j_stuff == TRUE){ print(paste("iter",iter,"/",J)) }
    linear_predictors_for_one_beta_draw_per_column <- cbind(linear_predictors_for_one_beta_draw_per_column,
                  table_region_rows%*%t(mcmc_values[iter,c("b_Intercept","b_fire_freq_std","b_mean_precip_std")]))
  }
  
  print("dim(linear_predictors_for_one_beta_draw_per_column)")
  print(dim(linear_predictors_for_one_beta_draw_per_column))
  print("(nb_donnes I * nb_iter_mcmc J)")
  
  simulations = matrix(nrow=nrow(linear_predictors_for_one_beta_draw_per_column),
                      ncol=ncol(linear_predictors_for_one_beta_draw_per_column))
  
  linear_predictors_beta_mean = table_region_rows%*%as.matrix(summary(mcmc_output)$fixed$Estimate)
  simulation_beta_mean = matrix(nrow=I,ncol=1)
  phi_for_beta_mean = summary(mcmc_output)$spec_pars$Estimate[1]
  zi_for_beta_mean = summary(mcmc_output)$spec_pars$Estimate[2]
  
  # browseURL("https://distribution-explorer.github.io/continuous/beta.html")
  require(gtools) # for inv.logit
  
  # beta_mean_prediction
  for(i in 1:I){
      
    draw_zero = rbinom(n=1,size=1,prob=zi_for_beta_mean)
    
    if(draw_zero==TRUE){simulation_beta_mean[i,1] <- 0}
    else{
      brms_theta = inv.logit(linear_predictors_beta_mean[i,1])
      R_shape1 = brms_theta*phi_for_beta_mean
      R_shape2 = (1-brms_theta)*phi_for_beta_mean
    
      simulation_beta_mean[i,1] <- rbeta(n=1,
                                         shape1 = R_shape1,
                                         shape2 = R_shape2)
    }
  }
    
  # predictions for all betas : for all i,j we make a gamma draw
  for(i in 1:I){
    
    if(print_i_j_stuff == TRUE){ print(paste("i",i,"/",I)) }

    
    for(j in 1:J){
                  brms_theta = inv.logit(linear_predictors_for_one_beta_draw_per_column[i,j])
                  brms_phi = mcmc_values[j,"phi"]
                  brms_zi = mcmc_values[j,"zi"]
                  
                  R_shape1 = brms_theta*brms_phi
                  R_shape2 = (1-brms_theta)*brms_phi
                  
                  draw_zero = rbinom(n=1,size=1,prob=brms_zi)
                  
                  if(draw_zero==TRUE){
                    # print(paste("draw_zero == TRUE"))
                    simulations[i,j] <- 0
                  }else{
                    # print(paste("draw_zero == FALSE"))
                    simulations[i,j] <- rbeta(n=1, shape1 = R_shape1, shape2 = R_shape2)
                  }
    }
    if(print_i_j_stuff == TRUE){print(paste("pour",J,"j"))}
  }
  
  # Quantiles for each simulation j
  {
  for(i in 1:I){
    table_region[i,c("pred_canopy_cover_quantile_inf",
                     "pred_canopy_cover_median",
                     "pred_canopy_cover_quantile_sup")] <- quantile(simulations[i,], probs = c(0.05,0.5,0.95))
    }
  
  
    plot(1:I,
         table_region$canopy_cover,
         xlab="i",
         ylab="canopy_cover"
    )
    lines(1:I,table_region[,"pred_canopy_cover_median"],col="pink",lty=1)
    lines(1:I,table_region[,"pred_canopy_cover_quantile_inf"],col="blue",lty=2)
    lines(1:I,table_region[,"pred_canopy_cover_quantile_sup"],col="darkblue",lty=2)
  }
  
  # Ordered :
  {

  indices_of_increasing_canopy_cover <- sort(table_region$canopy_cover, index.return=TRUE)$ix
  ordered_table_region <- table_region[indices_of_increasing_canopy_cover,]
  
    plot(1:I,
         ordered_table_region$canopy_cover,
         xlab="i",
         ylab="canopy_cover"
    )
    lines(1:I,ordered_table_region[,"pred_canopy_cover_median"],col="pink",lty=1)
    lines(1:I,ordered_table_region[,"pred_canopy_cover_quantile_inf"],col="blue",lty=2)
    lines(1:I,ordered_table_region[,"pred_canopy_cover_quantile_sup"],col="darkblue",lty=2)
  }
  
  ####### Sur les n premières valeurs
  
  n = min(100,nrow(table_region))
  # some datasets have less than 100 rows
  
  {
    plot(1:n,
         table_region$canopy_cover[1:n],
         xlab="i",
         ylab="canopy_cover",
         ylim=c(0,1)
    )
    lines(1:n,table_region[1:n,"pred_canopy_cover_median"],col="pink",lty=1)
    lines(1:n,table_region[1:n,"pred_canopy_cover_quantile_inf"],col="blue",lty=2)
    lines(1:n,table_region[1:n,"pred_canopy_cover_quantile_sup"],col="darkblue",lty=2)
  
    indices_of_increasing_rh98 <- sort(table_region$rh98, index.return=TRUE)$ix
    ordered_table_region <- table_region[indices_of_increasing_rh98,]
    
    plot(1:n,
         ordered_table_region$canopy_cover[1:n],
         xlab="i",
         ylim=c(0,1)
         # for some dataset, there are less than 100 points...
    )
    lines(1:n,ordered_table_region[1:n,"pred_canopy_cover_median"],col="pink",lty=1)
    lines(1:n,ordered_table_region[1:n,"pred_canopy_cover_quantile_inf"],col="blue",lty=2)
    lines(1:n,ordered_table_region[1:n,"pred_canopy_cover_quantile_sup"],col="darkblue",lty=2)
  }

  # 5 plots of reality vs predicted
  nb_of_plots = 5
  {
  
  print("mean(table_region$canopy_cover)")
  print(mean(table_region$canopy_cover))
  print("sd(table_region$canopy_cover)")
  print(sd(table_region$canopy_cover))
  
  for(j in sample(1:J,nb_of_plots,replace=FALSE)){
  
                    hist(table_region$canopy_cover,
                         freq=FALSE,
                         breaks=seq(0,1,by=0.02),
                         xlim=c(0,1),
                         main="true canopy_cover"
                    )
                    
                    hist(simulations[,j],
                         freq=FALSE,
                         breaks=seq(0,1,by=0.02),
                         xlim=c(0,1),
                         main = paste("betas n°",j)
                    )
                    
                    # print mean and sd vs truth
                    {
                    print(paste(
                      "mean(simulations[,j]) ( truth =",
                      round(mean(table_region$canopy_cover),3),
                      ")"
                      ))
                    print(round(mean(simulations[,j]),3))
                    print(paste(
                      "sd(simulations[,j]) ( truth =",
                      round(sd(table_region$canopy_cover),3),
                      ")"
                      ))
                    print(round(sd(simulations[,j]),3))
                    }
                    
                    # # predicted vs truth
                    # {plot(table_region$canopy_cover,
                    #       simulations[,j],
                    #       xlim=c(0,1),
                    #       ylim=c(0,1),
                    #       main = paste("betas n°",j,"cor=",
                    #                    round(cor(table_region$canopy_cover,simulations[,j]),
                    #                          2)
                    #                    )
                    # )
                    #   abline(0,1,col="red")}
                    # 
                    # sample_thing <- sample(1:I,40,replace=FALSE)
                    # 
                    # # just prediction of 40 random points
                    # {plot(table_region[sample_thing,"canopy_cover"],
                    #       simulations[sample_thing,j],
                    #       xlim=c(0,1),
                    #       ylim=c(0,1),
                    #       main = paste("betas n°",j,"cor=",
                    #                    round(cor(table_region$canopy_cover,simulations[,j]),
                    #                          2)
                    #                    )                                       
                    # )
                    #   abline(0,1,col="red")}
                    
                    
  } # end of the loop
  
  {plot(table_region$canopy_cover,
        simulation_beta_mean,
        xlim=c(0,1),
        ylim=c(0,1),
        main = paste("cor=",
                     round(cor(table_region$canopy_cover,simulation_beta_mean),
                           2)
                     )
  )
    abline(0,1,col="red")}

  sample_thing <- sample(1:I,40,replace=FALSE)

  # just prediction of 40 random points
  {plot(table_region[sample_thing,"canopy_cover"],
        simulation_beta_mean[sample_thing],
        xlim=c(0,1),
        ylim=c(0,1),
        main = paste("40 random points; cor=",
                     round(cor(table_region$canopy_cover,simulation_beta_mean),
                           2)
                     )
  )
    abline(0,1,col="red")}
  
  }
  
  moyennes <- vector(length = J)
  ecarts_types <- vector(length = J)
  
  for(j in 1:J){
    moyennes[j] <- mean(simulations[,j])
    ecarts_types[j] <- sd(simulations[,j])
    }
  
  # Histogramme des moyennes
  {hist(moyennes,
        freq=FALSE,
        breaks=50,
        xlim=c(min(moyennes)-0.05,max(moyennes)+0.05),
        main=paste(round(mean(table_region$canopy_cover),3),"; simus=",round(mean(moyennes),3))
        )
    abline(v=mean(moyennes),
           col="black")
    
    abline(v=mean(table_region$canopy_cover),
           col="blue")}
  
  # Histogramme des écarts-types
  {hist(ecarts_types,
        freq=FALSE,
        breaks=50,
        xlim=c(min(ecarts_types)-0.05,max(ecarts_types)+0.05),
        main=paste(round(sd(table_region$canopy_cover),3),"; simus=",round(mean(ecarts_types),3))
        )
    abline(v=mean(ecarts_types),
           col="black")
    abline(v=sd(table_region$canopy_cover),
           col="blue")}


} # END OF THE BIG LOOP
```

