---
title: "First test complete model"
output: html_document
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

```{r setup, echo=FALSE, include = FALSE}
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R")
getwd()
# Libraries
library(rjags)
library(dclone)
library(snow)
library(parallel)
library(doParallel)
```

```{r data_loading, echo=FALSE, include = FALSE}

table_region <- readRDS(
                file.path(
                  path_to_Savanna_structure_GEDI_folder,
                  "subsampling30avril",
                  "final_table_10km_associated_to_300km_cell.RDS")
                )

head(table_region,10)
# table(table_region$near_the_big_cell)

table <- cbind(table_region,table_region$x_TRUE,table_region$y_TRUE)
colnames(table)[15] = "x_TRUE2"
colnames(table)[16] = "y_TRUE2"

# ensuite enregistrer en geojson, faire l'intersection et recharger sur R

require(sf)

sf_obj <- st_as_sf(table,coords = c("x_TRUE2", "y_TRUE2"),crs = 4326)
# ces coords vont sauter du tableau l'export donc je les ai doublées

st_write(
         sf_obj,
         file.path(path_to_Savanna_structure_GEDI_folder,
                   "geojson_files",
                   paste0("table_pour_intersection.geojson")
                   ), delete_dsn = T
         )
```

```{r}
# A partir de là , on ajoute d'une valeur du raster densité de population à la couche vecteur .geojson :
# 
# traitement-> boite à outil -> sample raster values (fr : prélèvement des valeurs rasters vers ponctuels)
# préciser la couche raster
# échantilloné -> fichier .shp (=tableau géoréférencé (ne pas supprimer les tableaux connexes shx et prj), comme geojson)
# clic droit couche -> exporter as ...
# geocsv pas mal csv dont la première colonne est l'objet de géoréférencement wkt
# sinon csv standard

# Ainsi on a rajouté une colonne "densité de population" au tableau du bloc précédent

table2 <- read.csv(
  file.path(
  path_to_Savanna_structure_GEDI_folder,
  "geojson_files",
  "post_ajout_colonne_densite_pop.csv"
  ))

table2 <- table2[ complete.cases(table2) , ]
colSums(is.na(table2))

print(colnames(table))
print(colnames(table2))

colnames(table2) = c(colnames(table)[1:14],"densite_pop")

nrow(table2)
# 10923
table2 <- table2[ table2[,"densite_pop"]<10 , ]
nrow(table2)
# 6903

sf_obj <- st_as_sf(table2,coords = c("x_TRUE", "y_TRUE"),crs = 4326)
# ces coords vont sauter du tableau l'export donc je les ai doublées

st_write(
         sf_obj,
         file.path(path_to_Savanna_structure_GEDI_folder,
                   "data_pop_inf_10",
                   paste0("donnees_post_intersection.geojson")
                   ), delete_dsn = T
         )

write.csv(table2,file.path(path_to_Savanna_structure_GEDI_folder,"data_pop_inf_10","data_pop_inf_10.csv"))
```
