---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
# For the accents ? ? ? etc
options(Encoding="latin1")
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R",encoding="latin1")
# Setting the current path
path_to_R_folder = file.path(
                             path_to_Savanna_structure_GEDI_folder,
                             "R"
                             )
setwd(path_to_R_folder)
getwd()

# Libraries
library(fst)
library(ggplot2)

# # Pour avoir les pourcentages de donn?es manquantes :
# 
# # Chargement du tableau missing_data_percentages.csv
# 
# setwd(file.path(
#                 path_to_Savanna_structure_GEDI_folder,
#                 "figures"
#                 )
#       )
# 
# missing_data_percentages <- read.csv("missing_data_percentages.csv",row.names=1)
# 
# sub_missing_data_percentages <- missing_data_percentages[c("Guinean_forest-savanna",
#                                                            "West_Sudanian",
#                                                            "Sahelian_Acacia"),]
  
setwd(path_to_R_folder)
```

```{r}
# Chargement des donn?es des 3 ?cor?gions

setwd(path_to_GEDI_raw_data)
names = c("Guinean_forest-savanna","West_Sudanian","Sahelian_Acacia")
corresponding_tables = list()

i = 0

for (name in names){
  
  i <- i +1
  
    print(name)
  corresponding_table = fst::read.fst(paste0(name,".fst"))
  print(paste("Nb lignes :",round(nrow(corresponding_table),-3)))
  
  TRUE_FALSE_is_fire_freq_NA <- is.na(corresponding_table[,"fire_freq"])
  corresponding_table["fire_freq_NA"] <- TRUE_FALSE_is_fire_freq_NA
  
  # To replace the NA by zeros :
  corresponding_table[which(TRUE_FALSE_is_fire_freq_NA),"fire_freq"] <- 0
  
  # print("Mean_precip :")
  # print(summary(corresponding_table[,"mean_precip"]))
  
  corresponding_tables[[i]] <- corresponding_table
  
}

Guinean_table <- corresponding_tables[[1]]
Sudanian_table <- corresponding_tables[[2]]
Sahelian_table <- corresponding_tables[[3]]

rm(corresponding_table,i,name)
rm(TRUE_FALSE_is_fire_freq_NA)

setwd(path_to_R_folder)
```

```{r}
# Visualisation des trois zones ? travers les canopy_cover :

# Comptez 3 minutes pour l'affichage des graphiques
# (cartes d?j? dispos dans les figures)

for (i in 1:3){
  
  start <- Sys.time()

  name <- names[i]
  print(name)
  
  corresponding_table <- corresponding_tables[[i]]
  print(paste("Nb lignes :",round(nrow(corresponding_table),-3)))

  corresponding_table_without_canopy_cover_NA <- corresponding_table[
                                        complete.cases(
                                         corresponding_table[,c("canopy_cover")]
                                                       ),]
  print(" suppression des canopy_cover NA ")
  print(paste(
    "Nb lignes :",
     round(nrow(corresponding_table_without_canopy_cover_NA),-3),
     "soit",
     round(nrow(corresponding_table_without_canopy_cover_NA)/nrow(corresponding_table),2),
     "%"
  ))
  
  # Affichage :
  
  plot1 <- ggplot() +
    
  geom_raster(data = corresponding_table_without_canopy_cover_NA ,
              aes(x = x, y = y,
                  fill = canopy_cover)) +
  scale_fill_gradient(low = "palegreen", high = "forestgreen") +

  scale_alpha(range = c(0.15, 0.65), guide = "none") +
  ggtitle("canopy_cover") +
  coord_quickmap() +
  ggtitle(name)

  print(plot1)
  
  print(Sys.time() - start)
}
```

```{r}
# Visualisation des trois zones ? travers les rh98 :

# Comptez 3 minutes pour l'affichage des graphiques
# (cartes d?j? dispos dans les figures)

for (i in 1:3){
  
  start <- Sys.time()

  name <- names[i]
  print(name)
  
  corresponding_table <- corresponding_tables[[i]]
  print(paste("Nb lignes :",round(nrow(corresponding_table),-3)))

  # Pas de donn?es manquantes pour les rh98
  
  # Affichage :
  
  plot2 <- ggplot() +
    
  geom_raster(data = corresponding_table ,
              aes(x = x, y = y,
                  fill = rh98)) +
  scale_fill_gradient(low = "palegreen", high = "darkgreen") +

  scale_alpha(range = c(0.15, 0.65), guide = "none") +
  ggtitle("rh98") +
  coord_quickmap() +
  ggtitle(name)

  print(plot2)
  
  print(Sys.time() - start)
}

```

```{r}
# Premier test brms juste pour voir si brms encaisse le volume de donn?es
# m?me sans corr?lation spatiale pour commencer

print(round(nrow(Guinean_table),-3))

summary(Guinean_table[,"rh98"])
# On va tester sur le rh98 avec une loi Gamma pour commencer
# pour ne pas avoir le probl?me du beta inflated avec canopy_cover dans [0,1[

print(colnames(Guinean_table))

require(brms)

# get_prior donne la liste des priors utilis?s par d?faut (qu'on peut changer individuellement)
# avec la commande brms pour une formule donn?e

# Pour avoir des d?tails sur une loi et se(s) lien(s) pour un glm :

# vignette("brms_families")
# browseURL("https://rdrr.io/cran/brms/man/brmsfamily.html")

# Pour plus d'infos j'ai mis toute la doc dans Forest_savanna_project -> _Documents -> brms

default_prior = get_prior(
                          formula = rh98 ~ mean_precip + mean_temp  + fire_freq,
                          # +  (1 | machin) pour effet al?atoire machin
                          
                          data = Guinean_table,
                          
                          family = brmsfamily(family = "Gamma")
                          # ? voir comment sp?cifier le lien et lequel est utilis?
                          )

View(default_prior)

# On pourra mettre des priors loi normale au lieu des prior plats impropres pour la pluie etc.
```
```{r}
# start <- Sys.time()
# print(start)
# 
# mod <- brm(
# 
#             formula = rh98 ~ mean_precip + mean_temp  + fire_freq,
#             # +  (1 | machin) pour effet al?atoire machin
#             
#             data = Guinean_table,
#             
#             family = brmsfamily(family = "Gamma"),
#             # ? voir comment sp?cifier le lien et lequel est utilis?
# 
#             prior = NULL,
#             # prior = NULL pour utiliser les priors par d?faut,
# 
#             warmup = 10**3,
#             iter = 5*10**3,
#             thin = 10,
# 
#             chains = 3,
#             cores = 3,
#             # Number of cores to use when executing the chains in parallel.
#             
#             # control = list(adapt_delta = 0.95), 
#             # A named list of parameters to control the sampler's behavior.
#             # On peut ?tre amen? ? ajouter ce param?tre suite ? une erreur qui sugg?re
#             # de rajouter cette commande. Je ne sais pas pourquoi.
#             
#             silent = 0
#             # Pour avoir les d?tails de l'?volution de la cha?ne
#             )
# 
# print(Sys.time() - start)

# 1000 transitions using 10 leapfrog steps per transition would take 15755.6 seconds.
# i.e. 4 hours 20 minutes
# so 5*10**3 iters is one day.

# 1000 transitions 15700 secondes ?a fait 15 secondes l'it?ration
# Peut-?tre un probl?me de capacit? puisque R me dit unable to save this file.
```

```{r}
# setwd(path_to_R_folder)

# saveRDS(mod,file="test_brms_Guinean.RDS")
# mod <- readRDS("test_brms_Guinean.RDS")
```

```{r}
# summary(mod)
# plot(mod,ask=FALSE)
```

```{r}
require(brms)
# Essai sur un sous-?chantillon

# On enl?ve les NA pour ?tre s?r de la taille du sous-?chantillon
sub_Guinean_table <- Guinean_table[complete.cases(Guinean_table[,c("mean_precip",
                                                                       "mean_temp",
                                                                       "fire_freq")]
                                                 ),]
sub_Guinean_table <- sub_Guinean_table[1:10**5,]



start <- Sys.time()
print(start)

mod2 <- brm(

            formula = rh98 ~ mean_precip + mean_temp  + fire_freq,
            # +  (1 | machin) pour effet al?atoire machin
            
            data = Guinean_table,
            
            family = brmsfamily(family = "Gamma"),
            # ? voir comment sp?cifier le lien et lequel est utilis?

            prior = NULL,
            # prior = NULL pour utiliser les priors par d?faut,

            warmup = 10**3,
            iter = 5*10**3,
            thin = 10,
            
            file = "test_brms_Guinean_dom1.RDS",

            chains = 3,
            cores = 3,          # Number of cores to use when executing the chains in parallel.
            
            # control = list(adapt_delta = 0.95), 
            # A named list of parameters to control the sampler's behavior.
            # On peut ?tre amen? ? ajouter ce param?tre suite ? une erreur qui sugg?re
            # de rajouter cette commande. Je ne sais pas pourquoi.
            
            silent = 0
            # Pour avoir les d?tails de l'?volution de la cha?ne
            )

print(Sys.time() - start)

# 1000 transitions using 10 leapfrog steps per transition would take 304.2 seconds.
# Soit 1 it?ration = 0.3 seconde
# 5 000 it?rations = 1500 secondes = 25 minutes...

# Au final pour la cha?ne la plus rapide :
# Chain 3:  Elapsed Time: 1199.11 seconds (Warm-up)
# Chain 3:                21933.8 seconds (Sampling)
# Chain 3:                23132.9 seconds (Total)
# donc on est loin des 1500 secondes

# Chain 2:  Elapsed Time: 804.439 seconds (Warm-up)
# Chain 2:                28692.5 seconds (Sampling)
# Chain 2:                29497 seconds (Total)
# Chain 2: 

# pendant ce temps-l? la cha?ne 1 n'en est qu'? 40% :D
# Chain 1: Iteration: 2000 / 5000 [ 40%]  (Sampling)

# Chain 1:  Elapsed Time: 1563.88 seconds (Warm-up)
# Chain 1:                73514.6 seconds (Sampling)
# Chain 1:                75078.5 seconds (Total)

# > print(Sys.time() - start)
# Time difference of 20.87102 hours
# (sur mon ordi perso)

summary(mod)
plot(mod,ask=FALSE)
```
```{r}
setwd(path_to_R_folder)

# Pour enregistrer manuellement la cha?ne sans utiliser l'argument "file" dans brm() :

# saveRDS(mod,file="test_brms_Guinean2.RDS")
# mod2 <- readRDS("test_brms_Guinean2.RDS")

# Pour enregistrer en pdf le visuel des cha?nes :

# pdf("chaines_Guinean_100000_lignes.pdf")
# plot(mod,ask=FALSE)
# dev.off()
```

```{r}
posterior_summary(mod)

# posterior_samples.brmsfit
# (Deprecated) Extract Posterior Samples
# 
# Extract posterior samples of specified parameters. The posterior_samples method is deprecated.
# We recommend using the more modern and consistent as_draws_* extractor functions of the posterior
# package instead.

ok <- as.data.frame(mod)
View(ok)
# semble marcher mais les cha?nes sont mises ? la suite les une des autres
# Est-ce grave d'avoir de l'autocorr?lation entre it?rations pour une r?gression ?
# je ne sais pas
```

```{r}

```

```{r}

```

```{r}

```




