---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup}
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R")
# Setting the current path
path_to_R_folder = file.path(
                             path_to_Savanna_structure_GEDI_folder,
                             "R"
                             )
setwd(path_to_R_folder)
getwd()
# Libraries
library(fst)
library(ggplot2)
library(brms)
library(sf)
library(terra)
# Encoding :
print("é è û")
```

```{r}
# Loading of the 3 ecoregions

# Here I take the random subsamples 10**4 :

Guinean <- st_read(file.path(path_to_Savanna_structure_GEDI_folder,
                             "geojson_files",
                             "2_10_4_Guinean.geojson")
                   )
Sudanian <- st_read(file.path(path_to_Savanna_structure_GEDI_folder,
                             "geojson_files",
                             "2_10_4_Sudanian.geojson")
                   )
Sahelian <- st_read(file.path(path_to_Savanna_structure_GEDI_folder,
                             "geojson_files",
                             "2_10_4_Sahelian.geojson")
                   )

# I have not normalized these data (might be easier for the prior)
# but beyond the test should we do it ?
  
# To take the subsamples according to the grid (5 km ?) :

# Guinean <-
# Sudanian <-
# Sahelian <-
```

```{r}
# NA verification
colSums(is.na(Guinean))
colSums(is.na(Sudanian))
colSums(is.na(Sahelian))
```

```{r}
# all families' names (*) :
# browseURL("https://rdrr.io/cran/brms/man/brmsfamily.html")

require(brms)

# prior
default_prior = get_prior(
                          formula = rh98 ~ mean_precip + mean_temp  + fire_freq,

                          data = Guinean,
                          
                          family = brmsfamily(family = "Gamma")
                          # no info about the links in (*)
                          # unlike the beta inflated
                          )

View(default_prior)

# verify that the priors indeed found their way into Stan's model code
make_stancode(formula = rh98 ~ mean_precip + mean_temp  + fire_freq,

              data = Guinean,
                          
              family = brmsfamily(family = "Gamma"),
              # no info about the links in (*)
              # unlike the beta inflated
              
              prior = default_prior
              )
```


```{r}
# set_prior documentation

# set_prior(
#           prior,
#           prior A character string defining a distribution in Stan language
#           
#           class = "b",
#           The parameter class. Defaults to "b" (i.e. population-level effects).
#           See ’Details’ for other valid parameter classes.
#           
#           coef = "",
#           Name of the coefficient within the parameter class.
#           
#           
#           lb = NA,
#           Lower bound for parameter restriction.
#           Currently only allowed for classes "b".
#           Defaults to NULL, that is no restriction.
#           
#           ub = NA,
#           Upper bound for parameter restriction.
#           Currently only allowed for classes "b". 
#           Defaults to NULL, that is no restriction.
#           
#           )

# si met des bornes, est-ce que ça contredit pas une distribution non-bornée ?

# prior(): Alias of set_prior allowing to specify arguments as expressions without quotation marks.
```

```{r}
summary(Guinean)
```

```{r}
# all families' names (*) :
# browseURL("https://rdrr.io/cran/brms/man/brmsfamily.html")

prior_1 = c(
            prior(
                  normal(1400,100),
                  class="b",
                  coef = mean_precip
                  ),
            
            prior(
                  normal(26,4),
                  class="b",
                  coef = mean_temp
                  ),
            
            prior(
                  normal(0.25,0.5),
                  class="b",
                  coef = fire_freq
                  )
            )

View(prior_1)

# verify that the priors indeed found their way into Stan's model code
make_stancode(formula = rh98 ~ mean_precip + mean_temp  + fire_freq,

              data = Guinean,
                          
              family = brmsfamily(family = "Gamma"),
              # no info about the links in (*)
              # unlike the beta inflated 
              
              prior = prior_1
              )
```


```{r}
start <- Sys.time()
print(start)

mod2 <- brm(

            formula = rh98 ~ mean_precip + mean_temp  + fire_freq,

            data = Guinean,
            
            family = brmsfamily(family = "Gamma"),
            # no info about the links in (*)
            # unlike the beta inflated 

            prior = prior_1,

            warmup = 10**3,
            iter = 5*10**3,
            thin = 10,
            
            # to save/load the file automatically
            
            # file = file.path(path_to_GEDI_raw_data,
            #                  "outputs",
            #                  "Guinean_1.RDS"),

            chains = 3,
            cores = 3,          
            
            # control = list(adapt_delta = 0.95), 
            
            silent = 0
            # full comments
            )

print(Sys.time() - start)
```


```{r}
# all families' names :
# browseURL("https://rdrr.io/cran/brms/man/brmsfamily.html")

require(brms)

# prior :

# family = "zero_inflated_beta" might be sufficient for canopy_cover
# as we have values in [0,1[
# family = "zero_inflated_beta" should also work (takes [0,1])
# (coi parameter in addition) 

default_prior = get_prior(
                          formula = canopy_cover ~ mean_precip + mean_temp  + fire_freq,

                          data = Guinean,
                          
                          family = brmsfamily(
                                              family = "zero_inflated_beta",
                                              link = "logit",
                                              link_phi = "log",
                                              link_zi = "logit"
                                              )
                          )

View(default_prior)

# verify that the priors indeed found their way into Stan's model code
make_stancode(formula = canopy_cover ~ mean_precip + mean_temp  + fire_freq,

              data = Guinean,
                          
              family = brmsfamily(
                                  family = "zero_inflated_beta",
                                  link = "logit",
                                  link_phi = "log",
                                  link_zi = "logit"
                                  ),
              
              prior = default_prior
              )
```


```{r}
# all families' names :
# browseURL("https://rdrr.io/cran/brms/man/brmsfamily.html")

prior_2 = c(
            prior(
                  normal(1400,100),
                  class="b",
                  coef = mean_precip
                  ),
            
            prior(
                  normal(26,4),
                  class="b",
                  coef = mean_temp
                  ),
            
            prior(
                  normal(0.25,0.5),
                  class="b",
                  coef = fire_freq
                  )
            )

View(prior_2)

# verify that the priors indeed found their way into Stan's model code
make_stancode(formula = canopy_cover ~ mean_precip + mean_temp  + fire_freq,

              data = Guinean,
                          
              family = brmsfamily(
                                  family = "zero_inflated_beta",
                                  link = "logit",
                                  link_phi = "log",
                                  link_zi = "logit"
                                  ),
              
              prior = prior_2
              )
```


```{r}
start <- Sys.time()
print(start)

mod2 <- brm(

            formula = canopy_cover ~ mean_precip + mean_temp  + fire_freq,

            data = Guinean,
                          
            family = brmsfamily(
                                family = "zero_inflated_beta",
                                link = "logit",
                                link_phi = "log",
                                link_zi = "logit"
                                ),
            
            prior = prior_2,

            warmup = 10**3,
            iter = 5*10**3,
            thin = 10,
            
            # to save/load the file automatically
            
            # file = file.path(path_to_GEDI_raw_data,
            #                  "outputs",
            #                  "Guinean_2.RDS"),

            chains = 3,
            cores = 3,          
            
            # control = list(adapt_delta = 0.95), 
            
            silent = 0
            # full comments
            )

print(Sys.time() - start)
```

```{r}

```

```{r}

```

```{r}

```
