---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R")
# Setting the current path
path_to_R_folder = file.path(
                             path_to_Savanna_structure_GEDI_folder,
                             "R"
                             )
setwd(path_to_R_folder)
getwd()

# Libraries
library(fst)
library(rjags)
library(rstan)
library(brms)
stan_version() # [1] "2.32.2" le 21/03/24

# Rstan commands :
options(mc.cores = parallel::detectCores())
# if you are using rstan locally on a multicore machine and have plenty of RAM
# to estimate your model in parallel
rstan_options(auto_write = TRUE)
# which allows you to automatically save a bare version of a compiled Stan program
# to the hard disk so that it does not need to be recompiled (unless you change it).
# You will need to run these commands each time you load the rstan library.

# To verify rstan installation :
# example(stan_model, package = "rstan", run.dontrun = TRUE)

# Encoding :
print("é è û")

# See the number of cores of the machine : 
# browseURL("https://www.youtube.com/watch?v=lt-udg9zQSE")

require(parallel)
detectCores()
```

```{r}
# Lecture du fichier généré avec generate_sub_samples_of_all_regions.Rmd
# (données totales sans NA (sauf feu) ni doublons)

without_duplicate = readRDS(file = file.path(
                                             path_to_Savanna_structure_GEDI_folder,
                                             "rawdata",
                                             "without_duplicate.RDS"
                                             )
                            )

head(without_duplicate)

# require(janitor)
# duplicates <- janitor::get_dupes(without_duplicate, "x", "y")
# On doit avoir le message :
# -> No duplicate combinations found of: x, y
```

```{r}
# List of all ecoregions :
unique(without_duplicate[,"ecoregion"])

# Selection of ecoregions :
table_Guinean <- without_duplicate[without_duplicate[,"ecoregion"] == "Guinean_forest-savanna", ]
nrow(table_Guinean)

# "Guinean_forest-savanna" : 3 248 787 points
```

```{r}
# Selection of a subset of a table :

n = 10**4

sub_sample_indices <- sort(
                           sample(1:nrow(table_Guinean),
                                  n,
                                  replace=FALSE)
                          )

subtable_Guinean <- table_Guinean[sub_sample_indices,]
rownames(subtable_Guinean) <- 1:n
```

```{r}
rm(without_duplicate)
colnames(subtable_Guinean)

subtable_Guinean_archived <- subtable_Guinean
subtable_Guinean <- as.data.frame(
                    scale(subtable_Guinean[,c(
                                             "x",
                                             "y",
                                             "rh98",
                                             "canopy_cover",
                                             "fire_freq",
                                             "mean_precip",
                                             "mean_temp"
                                             )]
                          ,center=TRUE,scale=TRUE)
)
```

```{r echo=FALSE}
# Ok, faisons des tests STAN à présent sur subtable_Guinean

mcmc_STAN1 <- stan(

                  file = file.path(
                                   path_to_R_folder,
                                   'STAN_models',
                                   'model1.stan'
                                   ),
                  
                  data = list(
                              n = nrow(subtable_Guinean),
                              canopy_cover = subtable_Guinean$canopy_cover,
                              mean_precip = subtable_Guinean$mean_precip
                              ),
                  
                  init = list(
                              list(intercept = 0, beta = 1, sigma = 2),
                              list(intercept = 0, beta = 0, sigma = 3),
                              list(intercept = 1, beta = -2, sigma = 2),
                              list(intercept = 1, beta = -2, sigma = 10)
                              ),
                  
                  iter = 10**3,
                  thin = 10,
                  warmup = 10**2,
                  chains = 4, # default is always 4
                  cores = 4,
                  # we recommend setting it to be as many processors
                  # as the hardware and RAM allow (up to the number of chains).
                  verbose = TRUE
                  )

print(mcmc_STAN1)
```

```{r}
print(mcmc_STAN1)

require(shinystan)
launch_shinystan(mcmc_STAN1)
```

```{r}
# Comparaison avec brms

mod_brms1 <- brm(

            formula = canopy_cover ~ mean_precip,
            # +  (1 | machin) pour effet aléatoire machin

            data = subtable_Guinean,

            family = brmsfamily(family = "gaussian", link= "identity"),
            # brmsfamily(family = "gaussian", link= "identity") : standard linear regression
            
            prior = NULL,
            # prior = NULL pour utiliser les priors par défaut,

            iter = 10**3,
            thin = 10,
            warmup = 10**2,
            chains = 4, # default is always 4
            cores = 4,

            # control = list(adapt_delta = 0.95),
            # A named list of parameters to control the sampler's behavior.

            silent = 0
            # Pour avoir les détails de l'évolution de la chaine
            )
```

```{r}
print(mcmc_STAN1)
summary(mod_brms1)

# plot(mod_brms1,ask=FALSE)
```

```{r}
stancode(mod_brms1)
```

```{r}
mod_brms2 <- brm(

            formula = canopy_cover ~ mean_precip + fire_freq + mean_temp,
            # +  (1 | machin) pour effet aléatoire machin

            data = subtable_Guinean,

            family = brmsfamily(family = "gaussian", link= "identity"),
            # brmsfamily(family = "gaussian", link= "identity") : standard linear regression
            
            prior = NULL,
            # prior = NULL pour utiliser les priors par défaut,

            iter = 10**3,
            thin = 10,
            warmup = 10**2,
            chains = 4, # default is always 4
            cores = 4,

            # control = list(adapt_delta = 0.95),
            # A named list of parameters to control the sampler's behavior.

            silent = 0
            # Pour avoir les détails de l'évolution de la chaine
            )
```

```{r}
summary(mod_brms2)
stancode(mod_brms2)
```

```{r}
mcmc_STAN2 <- stan(

                  file = file.path(
                                   path_to_R_folder,
                                   'STAN_models',
                                   'model2.stan'
                                   ),
                  
                  data = list(
                              n = nrow(subtable_Guinean),
                              K = 3,
                              canopy_cover = subtable_Guinean$canopy_cover,
                              x = subtable_Guinean[,c("mean_precip",
                                                      "fire_freq",
                                                      "mean_temp")]
                              ),
                  
                  init = list(
                              list(intercept = 0, beta = list(0,1,2), sigma = 2),
                              list(intercept = 0, beta = list(0,4,2), sigma = 3),
                              list(intercept = 1, beta = list(-1,1,3), sigma = 2),
                              list(intercept = 1, beta = list(-2,2,2), sigma = 10)
                              ),
                  
                  iter = 10**3,
                  thin = 10,
                  warmup = 10**2,
                  chains = 4, # default is always 4
                  cores = 4,
                  # we recommend setting it to be as many processors
                  # as the hardware and RAM allow (up to the number of chains).
                  verbose = TRUE
                  )
```

```{r}
print(mcmc_STAN2)
print("yes")
summary(mod_brms2)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
