---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
# For the accents é ù û etc
options(Encoding="latin1")
# Cleaning the environment
rm(list=ls())
# Getting the paths
source("paths.R",encoding="latin1")
# Setting the current path
path_to_R_folder = file.path(
                             path_to_Savanna_structure_GEDI_folder,
                             "R"
                             )
setwd(path_to_R_folder)
getwd()

# Libraries
library(fst)
library(visdat)
# install.packages("visdat")
library(ggplot2)
# install.packages("betareg")
library(betareg)
# browseURL("https://www.jstatsoft.org/article/view/v034i02")

# Chargement du tableau missing_data_percentages.csv

setwd(file.path(
                path_to_Savanna_structure_GEDI_folder,
                "figures"
                )
      )

missing_data_percentages <- read.csv("missing_data_percentages.csv",row.names=1)

setwd(path_to_R_folder)
```

```{r}
# Générons des données simulées de loi Beta_(theta_i)
n = 10**4

phi = 3

if(phi<=0){stop("phi not in ]0,+inf[")}


x_1 = rnorm(n,3,1)
x_2 = runif(n,-2,2)

comb_lin = 0.3*x_1 - 2*x_2
# Lien logit :
mu = 1/(1+exp(-comb_lin))

y = rep(NA,n)

for(i in 1:n){
  
  p = phi*mu[i]
  q = phi*(1-mu[i])
  
  y[i] = rbeta(n=1,shape1=p,shape2=q)
  
  }

plot(1:n,y,ylim=c(0,1))

df = data.frame(cbind(y,x_1,x_2))
hist(y,breaks=50,main=paste("min",min(y),"max",max(y)))
```

```{r}
library(betareg)


model <- betareg(y ~ -1 + x_1 + x_2,
                 # | 1 => phi constant
                 data = df,
                 # subset,
                 # na.action=na.omit,
                 # weights,
                 # offset,
                 link = "logit",
                 link.phi = NULL,
                 # control = betareg.control(...),
                 model = TRUE,
                 y = TRUE,
                 x = FALSE
                 )

summary(model)

# Erreur dans betareg(y ~ -1 + x_1 + x_2, data = df, link = "logit", link.phi = NULL,  : 
#   invalid dependent variable, all observations must be in (0, 1)
```

```{r}
require(brms)
# Donne la liste des priors utilisés par défaut (qu'on peut changer individuellement)
# avec la commande brms pour une formule donnée

default_prior = get_prior(
                          formula = y ~ 1 + x_1 +x_2,
                          # +  (1 | machin) pour effet aléatoire machin
                          data = df,
                          )

View(default_prior)
```

```{r}
# vignette("brms_families")

# browseURL("https://rdrr.io/cran/brms/man/brmsfamily.html")

# browseURL("https://github.com/paul-buerkner/brms/issues/34")
# browseURL("https://discourse.mc-stan.org/t/understanding-parameters-of-beta-family-in-brms/21640")

mod <- brm(

            formula = y ~ 1 + x_1 +x_2,

            data = df,
            family = brmsfamily(family = "zero_one_inflated_beta",
                                link = "logit",
                                link_phi = "log",
                                link_zoi = "logit",
                                link_coi = "logit"),

            prior = NULL,
            # prior = NULL pour utiliser les priors par défaut,

            warmup = 100,
            iter = 5*10**3,
            thin = 10,

            chains = 3,
            cores = 3,
            # Number of cores to use when executing the chains in parallel.
            control = list(adapt_delta = 0.95), 
            # A named list of parameters to control the sampler's behavior.
            # J'ai dû  rajouter ce paramètre suite à une erreur qui suggérait
            # de rajouter cette commande.
            
            silent = 0
            )

```

```{r}
summary(mod)



```

```{r}
getwd()
#saveRDS(mod,file="test_brms2.RDS")
mod2 <- readRDS("test_brms2.RDS")

summary(mod2)
# exceptionnel
# bon ça aura pris une demie-heure
```

```{r}

# zoi : zero-one-inflated probability (alpha in the vignette)
# coi : conditional one-inflation probability (gamma in the vignette)
# density on 0 : alpha*(1-gamma)
# i.e. zoi*(1-coi)
# density on 1 : alpha*gamma
# i.e. zoi*coi
# density elsewhere : (1-alpha)*f(y)
# i.e. (1-zoi)*f(y)

# pdf("chaines.pdf")
# plot(mod,ask=FALSE)
# dev.off()
```


```{r}
# vignette("brms_families")

# browseURL("https://rdrr.io/cran/brms/man/brmsfamily.html")

# browseURL("https://github.com/paul-buerkner/brms/issues/34")
# browseURL("https://discourse.mc-stan.org/t/understanding-parameters-of-beta-family-in-brms/21640")
mod3 <- brm(

            formula = y ~ 1 + x_1 +x_2,

            data = df,
            family = brmsfamily(family = "zero_inflated_beta",
                                link = "logit",
                                link_phi = "log",
                                link_zi = "logit"),

            prior = NULL,
            # prior = NULL pour utiliser les priors par défaut,

            warmup = 100,
            iter = 10**3,
            thin = 10,

            chains = 3,
            cores = 3,
            # Number of cores to use when executing the chains in parallel.
            control = list(adapt_delta = 0.95), 
            # A named list of parameters to control the sampler's behavior.
            # J'ai dû  rajouter ce paramètre suite à une erreur qui suggérait
            # de rajouter cette commande.
            
            silent = 0
            )

```

```{r}
summary(mod3)
```

```{r}
getwd()
saveRDS(mod3,file="test_brms3.RDS")
mod3 <- readRDS("test_brms3.RDS")

summary(mod3)
```

```{r}
# pdf("chaines.pdf")
# plot(mod,ask=FALSE)
# dev.off()
```


